### ISSUE TITLE
How is metadata_path supposed to work?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#100]
My proposal is that, if it exists, it should be a subdirectory under the data_path.

If it were allowed to be any path in the submission, then when we're validating structure we don't necessarily know if a subdirectory is a data directory or a metadata directory... though we could encode the conventions for different submission types.

Do we have any examples of how DRTs actually want to use this to guide us?

This also impinges on downstream APIs... Do they prefer that all the data for a dataset be in a single directory, or can it be dispersed?

**Comment by cebriggs7135** [comment]
My guess is you're correct in saying metadata should be in a subdirectory of the data directory.

**Comment by mccalluc** [comment]
Ok, then this will only work when the directory schema also tells us we can expect an extra file. When we have an example that needs it, we'll do that.
