### ISSUE TITLE
Human readable report on which fields are used in which assays

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#1015]
As teams are developing new metadata schemas, they want to compare against existing field definitions so that terms can be reused where possible. Right now there's a spreadsheet that Chris maintains, but it would be less work, more accurate, and more up to date if this were part of the doc build process.

@cebriggs7135 :
- First column is the field name, second is the description, and following are boolean columns, one per assay type. Does that sound right? 
- Would any other information be useful, like the values for enums?
- Ordering: Alphabetically sort the rows and columns?
- What format(s) should be generated? TSV / HTML / Excel?
- With this in place would you be able to drop the spreadsheet, or are there other usecases that this doesn't cover?

**Comment by cebriggs7135** [comment]
@mccalluc 
Instead of a boolean for each field for each assay, I like having the fieldnames just copied across the rows for each relevant assay.
enums: values for enums would be very useful.
order: ordering field names alphabetically is OK.
format: Excel is most convenient.

**Comment by mccalluc** [comment]
Chris adds:
> My process is to give them a template by downloading the schema for the assay they say is most similar to their new assay.
>
> Then they can look through the master list of fields for other fields they might be interested in.

**Comment by mccalluc** [comment]
Chris confirmed in conversation that narrow columns with checkmarks would work.
