### ISSUE TITLE
atac -> sc-atac

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#102]
Clarify exactly what the name should be.

**Comment by cebriggs7135** [comment]
sc ATAC SEQ refers to single cell ATACseq, so "SC" is an important qualifier that distinguishes "bulk" (made from a mixture of cells like from a piece of tissue) from the single cell version.

**Comment by mccalluc** [comment]
@cebriggs7135 : To clarify:

In `assay_type`, these are the ATAC options. Should there be an "sc something"?: 
      - bulk ATAC
      - sci-ATAC-seq
      - snATAC

In `transposition_method`, these are the ATAC options. Above you say "sc ATAC SEQ": I need to know exactly what spacing and capitalization you prefer, and we need to be consistent.
      - scATACseq
      - BulkATACseq
      - snATACseq
      - sciATACseq

**Comment by cebriggs7135** [comment]
The ids as you show them above is correct, except for the uppercase B in BulkATACseq. Here they are as you wrote them above: - scATACseq
  - BulkATACseq
  - snATACseq
  - sciATACseq

For consistency, you probably want a lowercase B for bulkATACseq:
- scATACseq
  - bulkATACseq
  - snATACseq
  - sciATACseq

**Comment by mccalluc** [comment]
Will confirm with Chris, but for both I think we want:
```
scATACseq
bulkATACseq
snATACseq
sciATACseq
```

**Comment by mccalluc** [comment]
(got confirmation)
