### ISSUE TITLE
Change directory schema for new CODEX data

### ISSUE THREAD

**Issue by VasylVaskivskyi** [hubmapconsortium/ingest-validation-tools#1053]
We created a CODEX common metadata standard for internal use in HubMAP. All the acquisition metadata will be contained in one file `experiment.json` instead of five: `segmentation.json, channelnames.txt, channelnames_report.csv, exposure_times.csv`. Now we need to adjust directory schema. 
It should look like this:

```
codex_dataset/
|--- raw
|     |--- experiment.json
|     |
|     |--- Cyc001_reg001  
|     |     |--- 1_00001_Z001_CH1.tif
|     |     |--- 1_00001_Z001_CH2.tif
|     |     |              ...
|     |     `--- 1_0000N_Z00N_CHN.tif
|     |     
|     `--- Cyc001_reg002  
|           |--- 2_00001_Z001_CH1.tif
|           |--- 2_00001_Z001_CH2.tif
|           |             ...
|           `--- 2_0000N_Z00N_CHN.tif
|    
`--- processed 
         `--- TMC's processed data
```

To preserve backwards compatibility, I propose to just set for these files `required: False`
https://github.com/hubmapconsortium/ingest-validation-tools/blob/f2da75a7eea01be75c2b62d1574d3b7fbab312d0/src/ingest_validation_tools/directory-schemas/codex.yaml#L47-L50

https://github.com/hubmapconsortium/ingest-validation-tools/blob/f2da75a7eea01be75c2b62d1574d3b7fbab312d0/src/ingest_validation_tools/directory-schemas/codex.yaml#L63-L66

**Comment by icaoberg** [comment]
@VasylVaskivskyi you need me to remove the PDFs files and other reports as well?

**Comment by VasylVaskivskyi** [comment]
@icaoberg I used a PDF file with some imaging information only a couple of times to verify something. But no every provider gives them to us, so I think it's okay to keep them as is.
