### ISSUE TITLE
Can't get validation to run

### ISSUE THREAD

**Issue by pxh251** [hubmapconsortium/ingest-validation-tools#1055]
Hi, I tried to run the validation and here's the error: 
Can you help me please? Thank you very much!

(base) H4TGN1F9PN7C:ingest-validation-tools hup2$ python3 src/validate_tsv.py --schema metadata --path /Users/hup2/Desktop/scatacseq-metadata.tsv 
Traceback (most recent call last):
  File "/Users/hup2/ingest-validation-tools/src/validate_tsv.py", line 7, in <module>
    from ingest_validation_tools.error_report import ErrorReport
  File "/Users/hup2/ingest-validation-tools/src/ingest_validation_tools/error_report.py", line 2, in <module>
    from yaml import Dumper, dump
[scrnaseq-metadata copy.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/8179493/scrnaseq-metadata.copy.txt)

ModuleNotFoundError: No module named 'yaml'

**Comment by mccalluc** [comment]
You need to install dependencies. See the [README](https://github.com/hubmapconsortium/ingest-validation-tools#for-data-submitters-and-curators):

```
pip install -r requirements.txt
```
