### ISSUE TITLE
Clarify how curator can run validation

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#106]
We want a way to quickly validate submissions, allowing Chris to iteratively fix the TSV and get the files in the right directory structure.

- Chuck would prefer not to be responsible for maintaining another web application.
- Curator running the tool locally will not work because it can't validate the structure and consistency of subdirectories ...
- Command-line tool to validate just the TSV is already available, but I don't think that solves this.
- This will depend on html reporting (#105).

Notes: 
- I have worked with a model of submissions being discrete directories on globus, consisting of one metadata.tsv, with subdirectories corresponding to the rows of the TSV. If that is not the correct model, please file an issue.
- This is all describing the systems we want to have going forward, and it would not work with the current submission directories. I think this is more likely to be successful if I work from a clear model going forward, but if you think this code should also handle the current structures on globus, please file and issue describing what the behavior should be.

**Comment by ngehlenborg** [comment]
Just a quick comment on one aspect of this issue: "with subdirectories corresponding to the rows of the TSV". That is too restrictive. It should also be possible to reference individual files with a row in the table.

**Comment by mccalluc** [comment]
We'll need to run it locally: Here are the run modes I think we need to accomodate:
- `tsv`: Just validate a local TSV: No validation of directory structure. *Basic sanity check.*
- `tsv` + `globus`: Validate a local TSV, and check directory structure on globus. *What Chris will typically use.*
- `globus`: Validate directory structure (containing a metadata.tsv) on globus. *Run full validation remotely.*
- `dir`: Validate local directory. *Tests and (eventually) ingest pipeline.*

**Comment by mccalluc** [comment]
(Just renamed the options above: Nils had initially suggested `--schema` but I think that was because of confusion: The actual schema to validate against is a separate parameter. And I've transposed the word order of the two-word options.)

**Comment by mccalluc** [comment]
Ok, those flags have been added to argparse, and some of them work. This issue was to clarify requirements, and that's done.
