### ISSUE TITLE
Issues building test.sh on branch icaoberg-nanodesi

### ISSUE THREAD

**Issue by icaoberg** [hubmapconsortium/ingest-validation-tools#1075]
I merged main into icaoberg-nanodesi so that it can support directory structure versioning.

Following the instructions on 

https://github.com/hubmapconsortium/ingest-validation-tools#for-developers-and-contributors

I ran the following on branch icaoberg-nanodesi

```
python -m venv .
source ./bin/activate
pip install --upgrade pip
pip install -r requirements.txt
pip install -r requirements-dev.txt
./test.sh
```

and I get the following output. See attached document.

[output.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/8566247/output.txt)

**Comment by mccalluc** [comment]
Tests scan all the files under the checkout: You’ve added bin, and so there are extra files that don’t pass linting and tests (`ERROR collecting bin/vba_extract.py`). You seem to also have conda installed: I’d suggest using just conda instead of trying to mix the two.

**Comment by icaoberg** [comment]
@mccalluc it worked. Thanks!

**Comment by mccalluc** [comment]
@icaoberg -- Can this be closed?

**Comment by mccalluc** [comment]
Closing. Reopen if there's any work for me here.
