### ISSUE TITLE
Get explicit buy-in from Nils+PSC folks on abstract model of assay data submission

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#108]
Original:

<blockquote>
<strike>

@shirey: I recognize that some hacks might be needed to get the files already on Globus ingested, but I want to be sure we now have the same model of how assay submission will work when it is moving smoothly.

A submission will require:
- a Donor HuBMAP Display ID
- a Sample HuBMAP Display ID
- a Type
- and a Globus directory containing only:
  - a metadata.tsv, with columns determined by the Type
  - subdirectories, or single files, in a 1-to-1 relationship with the rows of the TSV.

(Single rows/subdirectories may be datasets, or datasets might be multiple joined rows: That doesn't matter at this level of detail.)

If this model is correct, please confirm.

If it's not correct, let's talk, or describe the problem here, as you think best.

</strike>
</blockquote>

Revised:

<blockquote>

After talking with @shirey, persuaded that the TMCs really want to submit multiple assay types at once, and that a submission will not be limited to a single Sample (although we will keep the constraint that it comes from a single Donor). So all together:

A submission will require:
- a Donor HuBMAP Display ID
- a Globus directory containing:
  - one or more `<type>-metadata.tsv` files. (**This is slight change from what we discussed, Bill, but there needs to be something to say what to expect in a given file.**)
  - top-level subdirectories, or single files, in a 1-to-1 relationship with the rows of the TSV. (**Is it ok to restrict this to the top-level, or do we need to accommodate multiple assays in nested subdirectories?**)

</blockquote>

Note: Provenance chain will be constructed only from the Display IDs in metadata.tsv: We no longer have an ID coming in from the submission form to double-check against. Chuck is willing to live with his discomfort about this decision.

Question: What portion of this is on the critical path for May? If some parts aren't, should it be de-prioritized?

**Comment by cebriggs7135** [comment]
Can you draw a diagram illustrating the proposed folder/file structure described above?

**Comment by mccalluc** [comment]
`assay-x-metadata.tsv`:
| donor_id | tissue_id | ... | assay_type | ... | data_path |
| -- | -- | -- | -- | -- | -- |
| ABC123 | ABC123-1-1-1 | ... | assay-x | ... | assay-x.xml |
| ABC123 | ABC123-1-1-2 | ... | assay-x | ... | assay-x-dir |

`assay-y-metadata.tsv`:
| donor_id | tissue_id | ... | assay_type | ... | data_path |
| -- | -- | -- | -- | -- | -- |
| ABC123 | ABC123-1-1-1 | ... | assay-y | ... | assay-y.xml |
| ABC123 | ABC123-1-1-2 | ... | assay-y | ... | assay-y-dir |

Submission directory on Globus:
```
assay-x-metadata.tsv
assay-y-metadata.tsv
assay-x.xml
assay-y.xml
assay-x-dir/
assay-y-dir/
```

**Comment by shirey** [comment]
@mccalluc This looks good.  @jswelling Does this match what you were thinking?

**Comment by ngehlenborg** [comment]
Looks ok to me but I have two questions about this note: "Provenance chain will be constructed only from the Display IDs in metadata.tsv: We no longer have an ID coming in from the submission form to double-check against." 

  1. What submission form is @mccalluc referring to?
  1. Are the "Display IDs" the same as HuBMAP IDs?

**Comment by mccalluc** [comment]
> What submission form is @mccalluc referring to?

Sorry I meant the ingest-ui web interface.

> Are the "Display IDs" the same as HuBMAP IDs?

To try to avoid confusion, I'll try to be consistent in using "HuBMAP Display ID" to mean the IDs like "ABC123" for Donors, or "ABC123-LK-1-1-1" for Samples.

**Comment by ngehlenborg** [comment]
@shirey @mccalluc @cebriggs7135: those IDs seem to be lab-specific. How do we avoid duplication? Shouldn't we be asking them to include the HuBMAP IDs for donors, samples, etc?

**Comment by shirey** [comment]
@ngehlenborg The ids that Chuck is referencing are generated by the tissue registration/provenance UI and displayed there.  They're the ids that the user sees when registering tissue.

**Comment by ngehlenborg** [comment]
@shirey: Ok. Sorry for being nitpicky here but I think identifiers are extremely critical because people will use them to reference data: does everything that has an "ABC123" (for Donors) or "ABC123-LK-1-1-1" (for Samples) identifier also a HuBMAP identifier (HBM...)?

If there is such an identifier, we would want to display those on the portal and generally would want to use them for public consumption. 

In essence, my question is if we could just use the HuBMAP identifiers (assuming they exist) for everything to avoid confusion (even if that is just at the level of submitters).

**Comment by mccalluc** [comment]
I thin the model is settled. I've filed https://github.com/hubmapconsortium/portal-ui/issues/170 to pin down the IDs. Closing.
