### ISSUE TITLE
Error when running test.sh

### ISSUE THREAD

**Issue by icaoberg** [hubmapconsortium/ingest-validation-tools#1084]
@mccalluc I am trying to run `test.sh` on the `icaoberg-seqfish` branch but I am getting this error that I don't know how to interpret. Any guidance would be welcomed

```
bash ./test.sh 
::group::flake8
::endgroup::
::group::mypy
src/ingest_validation_tools/validation_utils.py:26: error: Incompatible return value type (got "List[Dict[str, str]]", expected "List[OrderedDict[Any, Any]]")
Found 1 error in 1 file (checked 1 source file)
```

**Comment by icaoberg** [comment]
@mccalluc ended being a Python version issue. Seems I have issues with Python 3.9 + mypy so using Python 3.7 fixed the issue.

**Comment by mccalluc** [comment]
Actually, I'd like to make it more robust... particularly for newer python versions. Thanks for filing.
