### ISSUE TITLE
Change LC-MS directory schema: accept .raw and .d directories under the raw_data directory

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-validation-tools#1097]
Please make the following change to the pattern accepted under the `raw_data `directory:

In addition to **files** with the `.raw` and `.mzML` extension, also allow **directories** with the following extensions: `.raw` and `.d`.

@icaoberg will evaluate this request, and if it can move forward,
will file a PR for @pdblood to review,
and @mccalluc will make sure tests pass before merging.

**Comment by mccalluc** [comment]
@pdblood 
- Is there any expectation that this data will be usable downstream? The proliferation of formats makes that much less likely.
- I don't need to be involved in review of directory schema changes: Ivan has responsibility for making sure there's a green checkmark, and that's worked well.
