### ISSUE TITLE
Change LC-MS directory schema: make ID_metadata required and update to allow .txt, .tsv, and .csv, in addition to .xml

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-validation-tools#1098]
Please make the `ID_metadata/` directory a **required** directory. Also, update the pattern to allow files with extensions `.txt`, `.tsv`, and `.csv`, **in addition** to the existing `.xml`.

This was agreed upon by the LC-MS assay team at the annual meeting.

@icaoberg will evaluate this request, and if it can move forward,
will file a PR for @pdblood to review,
and @mccalluc will make sure tests pass before merging.

**Comment by mccalluc** [comment]
@pdblood 
- Is there any expectation that this data will be usable downstream? The proliferation of formats makes that much less likely.
- I don't need to be involved in review of directory schema changes: Ivan has responsibility for making sure there's a green checkmark, and that's worked well.
