### ISSUE TITLE
Delimit YAML in text output of validate_upload

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/ingest-validation-tools#1099]
The text output of validate_upload.py consists of a section of free text followed by a section of YAML containing schema version info &etc. There is no explicit delimiter between the two sections, and since the free text section is of variable length confusion may result.  Unfortunately there is external software which explicitly looks for the string 'No Errors' as the first line, so adding a prefix to the text section is problematic.

One could add a prefix character to all the YAML lines, as long as that character is not itself YAML syntax- for example, delimiting with '#' would be problematic because stripping the prefix from YAML comment lines would be ambiguous.  Alternately, inserting a known break line like '# yaml follows' would be a possible solution.

**Comment by mccalluc** [comment]
@jswelling -
> Unfortunately there is external software which explicitly looks for the string 'No Errors' as the first line, so adding a prefix to the text section is problematic.

What software is this? I had understood that you were using it in python, rather than wrapping the CLI, or are there (at least) two different usages on your side?

**Comment by jswelling** [comment]
The software that generates the table of unpublished datasets looks for validation_report.txt in the top level directory, and declares the dataset to have been validated if that file is present and starts with 'No Errors'.  This feature is pretty obsolete now that data is usually provided in the form of Uploads, so it could be disabled.  If the desired solution is to modify that first line, an issue should be created in ingest-pipeline to disable this check.

**Comment by mccalluc** [comment]
Filed https://github.com/hubmapconsortium/ingest-pipeline/issues/635; Closing this.
