### ISSUE TITLE
metadata with 'NA' in contributors path passes local validation

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/ingest-validation-tools#1112]
The attached metadata.tsv file with 'NA' in the contributors path passes local validation.
[20220502_TMC_Laurent_BulkATACseq_metadata_concatPaths.tsv.gz](https://github.com/hubmapconsortium/ingest-validation-tools/files/8970239/20220502_TMC_Laurent_BulkATACseq_metadata_concatPaths.tsv.gz)

**Comment by mccalluc** [comment]
On slack: 
>  The metadata.tsv contains 'NA' in that column.  Maybe that somehow passed validation?  The only alternative is that the provider did not do local testing, and they were quite emphatic that they had done so.

- If this was validated as a TSV, then it is unsurprising that this did not fail. Are you requesting special handling for the string "NA"?
- #1110 addresses confusion about TSV vs Upload validation.
- If this was validated as a submission, then that is a bug. I will investigate that possibility and update here.

**Comment by mccalluc** [comment]
@jswelling - I've confirmed that changing the contributors_path to "NA" will cause upload validation to fail:
```
src/validate_upload.py --local_directory examples/dataset-examples/good-codex-akoya-directory-v1-with-dataset.json/upload --dataset_ignore_globs 'ignore-*.tsv' '.*' --upload_ignore_globs 'drv_ignore_*' --offline --output as_md | perl -pne 's/(Time|Git version): .*/\1: WILL_CHANGE/'
2,11c2,15
< No errors!
< Time: WILL_CHANGE
< Git version: WILL_CHANGE
< Directory: examples/dataset-examples/good-codex-akoya-directory-v1-with-dataset.json/upload
< TSVs:
<   name-just-needs-to-end-with-metadata.tsv:
<     Schema: codex
<     Metadata schema version: '1'
<     Directory schema versions:
<     - 1-with-dataset-json
---
> Metadata TSV Errors:
>   ? examples/dataset-examples/good-codex-akoya-directory-v1-with-dataset.json/upload/name-just-needs-to-end-with-metadata.tsv
>     (as codex)
>   : Internal:
>     - On row 2, column "contributors_path", value "NA" fails because "N/A" fields
>       should just be left empty
>     External:
>       row 2, contributors examples/dataset-examples/good-codex-akoya-directory-v1-with-dataset.json/upload/NA: File
>         does not exist
> Reference Errors:
>   No References:
>     Files:
>     - contributors.tsv
> Hint: 'If validation fails because of extra whitespace in the TSV, try:
12a17
>   src/cleanup_whitespace.py --tsv_in original.tsv --tsv_out clean.tsv'
```
I'm not sure what other action you want taken here.

**Comment by mccalluc** [comment]
No reproducer. Closing for now, but feel free to re-open if you can provide more information.
