### ISSUE TITLE
contributors.tsv for HCA should be required

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#1113]
It was specifically not required [when originally authored](url), but Bill says:
> HCA Datasets should definitely require contributors (and contacts) like all other datasets.

**Comment by mccalluc** [comment]
@shirey:
- Whose approval is needed on this? You? Joel? Nils? new curator?
- Is this a correction that should be made in place, or should a new version be made?
- If a new version is made, should the old version be deprecated? (Since we are the only ones providing HCA data, this probably doesn't matter much.)
- Should other changes be made to the schema, to bring it up to date with the regular, non-HCA schema? 

```
$ diff docs/scrnaseq{-hca/v0.yaml,/v0.yaml} | wc -l
     263
$ diff docs/scrnaseq{-hca/v0.yaml,/v3.yaml} | wc -l
     331
```

**Comment by shirey** [comment]
@mccalluc Curation should be made aware of this.- @bhonick let me know if you want to discuss.

**Comment by bhonick** [comment]
@mccalluc For now, let's make contributors.tsv required for HCA data, but not other changes.

**Comment by mccalluc** [comment]
@bhonick : My interpretation is that you want HCA updated in place, rather than versioned, and that you do not want any of the updates from the regular scRNA-seq. Please confirm or clarify.

**Comment by bhonick** [comment]
@mccalluc Could you explain the difference between updating in place and versioning in this context? Thanks!

**Comment by mccalluc** [comment]
Joel's explanation: 
> The question of 'update in place' vs. 'define a new version' comes down to, should Chuck change the existing metadata schema for HCA to add the requirement for contributors.tsv, or create a new version, version 1.  I think the easier answer would be to change the schema in place because it reduces complexity, but it has a cost.  The problem is that it would cause the metadata.tsv files in the existing 5 HCA primary datasets to be invalid.  We would have to fix them in a two step process: (1) edit each metadata.tsv file and data directory to add a 'contributors_path' column entry that is not empty, and add a contributors.tsv file containing the appropriate data. (2) Update the Neo4J database manually to add those links.  Even so, I advocate for updating the schema in place.

**Comment by bhonick** [comment]
@mccalluc I agree with what Joel proposes about updating the schema in place, even with the cost associated.
