### ISSUE TITLE
Issues when running tests

### ISSUE THREAD

**Issue by icaoberg** [hubmapconsortium/ingest-validation-tools#1133]
When running `bash ./test.sh` on `main` I see this warning message

```
Trying to read examples/cleanup-examples/latin-1.input.tsv as utf-8...
Read failed: 'utf-8' codec can't decode byte 0xa0 in position 24: invalid start byte
```

**Comment by sunset666** [comment]
The response is the intended behavior for the test, trying to read a latin-1 encoded file as utf-8 will fail. Subsequent step attempts with a consistent encoding and get a successful answer.
