### ISSUE TITLE
Change ... directory schema: ...

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/ingest-validation-tools#1253]
Hi @j-uranic & @jpuerto-psc , the following changes should be made to this Histology directory schema:

1) `raw\/images\/[^\/]+\.xml` should be merged with `raw\/images\/[^\/]+\.(?:scn|vsi|ndpi|svs|czi|tiff)`

2) The following three files should be made optional:

lab_processed/annotations/[^/]+-objects.csv.

lab_processed/annotations/[^/]+.segmentations.ome.tiff.

lab_processed/annotations/segmentation-masks.csv.

I have advocated for them to be made optional until a different way is determined to integrate them into the schema. 

3) The definition for `*ome-tiff.channels.csv` has been updated to the following:

This file provides essential documentation pertaining to each channel of the accommpanying OME TIFF. The file should contain one row per OME TIFF channel. The required fields are detailed here https://docs.google.com/spreadsheets/d/1xEJSb0xn5C5fB3k62pj1CyHNybpt4-YtvUs5SUMS44o/edit#gid=0

**Comment by j-uranic** [comment]
@bhonick These fixes have been deployed.
