### ISSUE TITLE
Add "Stored as 4 degrees Celsius" option to Sample Block preparation_condition

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/ingest-validation-tools#1300]
For Sample Block preparation_condition please add the following option: "Stored as 4 degrees Celsius"

Change is minor and is appropriate for both HuBMAP and SenNet

Assigning to Josef
```[tasklist]
### Tasks
```

**Comment by johardi** [comment]
@HerrLufty Could you please ask with the requester whether the term "Stored in refrigerator" is still okay? This term already exists within our "storage_method" category, denoting the practice of storing a specimen at 4 degrees Celsius. 

For reference, the standard definition of a refrigerator can be found here: [NCIT Ontology - Refrigerator Definition](https://bioportal.bioontology.org/ontologies/NCIT/?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C178971), which says:
```
A storage container used to store perishable items, typically around 4 degrees Celsius but not below 0 degrees Celsius.
```
