### ISSUE TITLE
New preparation_instrument_model for H&E Histology

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/ingest-validation-tools#1301]
Please register and add the following preparation_instrument_model  for H&E Histology

Leica ST5020 Multistainer

Instrument has been discontinued. No Leica URL available.

Reseller URL:

https://www.gmi-inc.com/product/leica-st5020-multistainer-slide-stainer/

Backward compatible

Appropriate for HuBMAP and SenNet

Requested by Anthony Corbett

**Comment by johardi** [comment]
Did the data providers mention this URL from Leica? https://www.leicabiosystems.com/us/histology-equipment/he-slide-stainers-special-stainers-coverslippers/leica-st5020-cv5030/

If the URL doesn't represent the device properly, I can use the reseller URL instead.

**Comment by HerrLufty** [comment]
That has a cover slipper as well (cv5030) which is also discontinued. I sent them that URL, but haven't heard back.

Anthony is pretty good with details, so I'm assuming it's the st5020 only.

**Comment by johardi** [comment]
* New term is added to HRAVS v2.3.16
* Updating Histology spreadsheet files; See: https://github.com/hubmapconsortium/dataset-metadata-spreadsheet/commit/4c9c28292206257ed0da20c34213a20a35bab156

**Comment by jpuerto-psc** [comment]
@johardi - our documents just point to the "latest", so there is no need to request an update here for those changes. If there is a change to the metadata_schema_id, then we need to request updates. Thanks!
