### ISSUE TITLE
Pre-fill enums in row below header?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#141]
@cebriggs7135 : Regarding the enums, do you think it would make it any easier for the TMCs if we we prefilled one row with just the enums, so instead of copy-and-paste from the doc, they can just delete the ones that don't apply? Would that make their lives easier?

**Comment by mccalluc** [comment]
@cebriggs7135 : Do you have opinions about this? It would be easy to do, but if it's not going to make people's lives easier, no reason to do it, either.

**Comment by cebriggs7135** [comment]
That sounds good.
