### ISSUE TITLE
Validate seqfish directory structure

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#150]
@cebriggs7135 : Has any seqfish data been put on globus? If possible, I would like to compare what people are actually doing to the spec before implementing.

**Comment by mccalluc** [comment]
(Chris will ping Nico to see if the docs are stable and there is an example on globus.)

**Comment by mccalluc** [comment]
@cebriggs7135 : any progress?

**Comment by cebriggs7135** [comment]
Here's a seqFISH dataset in Globus:
https://app.globus.org/file-manager?origin_id=28bbb03c-a87d-4dd7-a661-7ea2fb6ea631&origin_path=%2FCalifornia%20Institute%20of%20Technology%20TMC%2F9f37a9b1f6073e6e588ff7e0dd9493b5%2F
![Screen Shot 2020-05-18 at 1 06 29 PM](https://user-images.githubusercontent.com/8284878/82240494-8518bb00-9908-11ea-9feb-7e851f35080a.png)
![Screen Shot 2020-05-18 at 1 06 23 PM](https://user-images.githubusercontent.com/8284878/82240496-85b15180-9908-11ea-8a55-bebf419f893d.png)

**Comment by mccalluc** [comment]
@cebriggs7135 :
- Do `pos12` through `pos17` altogether describe a dataset, or is each one of those its own dataset?

Within the directory, what kind of structure should we expect? Perhaps:
```
AllHybRegistrationCheck-*.tif
dapi-tform-*.csv
imagesHybDapi-*.mat
preProcessedData-*.mat
preprocessedImages-*.tif
```

**Comment by mccalluc** [comment]
*All* directory schemas need to be filled in. Closing per-assay-type issues.
