### ISSUE TITLE
Handle the CODEX src directories

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#171]
From #170. Actual data looks like:
```
src_CX_19-003_LN_R3
├── cyc001_reg001_191213_124421
│   ├── 1_00001_Z001_CH1.tif
│   ├── ...
│   └── 3.gci
...
├── channelnames.txt
├── experiment.json
├── exposure_times.txt
└── segmentation.json
```
Change the schema to reflect this.

@cebriggs7135 : This is taking us _away_ from the structure in your doc... Does the original doc need to be updated? Of do you want to point at the samples?

**Comment by cebriggs7135** [comment]
Waiting to find out what a .gci file is form Marda.

**Comment by mccalluc** [comment]
see #179 ... it can be ignored.
