### ISSUE TITLE
Handle CODEX drv directories

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#172]
From #170. CODE drv directories have a _very_ complex structure. Do we...
- not ingest drv?
- specify just the top level directories in the structure?
- specify it all the way down?
- something else?

**Comment by mccalluc** [comment]
We're not going to change our code to accommodate this: It's up to Joel.

**Comment by ngehlenborg** [comment]
Since we have a pipeline in place that converts data from raw to derived data, we will not release the derived data uploaded by the submitter.
