### ISSUE TITLE
How to handle UCSD sc-ATAC-seq?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#178]
From Slack:
> Joel Welling: For UCSD sc-ATAC-seq, is there a plan for how you’ll work with the current organization of files on Globus? The problem is that they’ve created directories per sample on globus, and the files for all the data sets under that sample are comingled below that. In the TSV, they’ve filled in data_path with strings like BUKMAP_20190529A.BUKMAP_2019529_SNARE2-AC_SR2_P2_N502_S2_R[1-3].fastq.gz (Note the [1-3].)
>
>If you’ve got a plan, great! If you don’t have a plan, is there a tweak I can give to the validator that would let it be used here? … perhaps accept path globs in addition to paths?
>
> Or would you want to programmatically move files around on globus so you do have tidy sub-directories?

**Comment by cebriggs7135** [comment]
Each toss has 12 sequences, each in triplicate as show [R1-3]
<img width="1097" alt="Screen Shot 2020-04-23 at 2 58 23 PM" src="https://user-images.githubusercontent.com/8284878/80138521-ebf9bd00-8572-11ea-814e-4f9bf5ce88d1.png">

**Comment by mccalluc** [comment]
Chris says not needed. Closing.
