### ISSUE TITLE
Directory spec for sc-rna-seq

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#183]
@cebriggs7135 : Can you get me an example of a sc-rna-seq submission? Thanks! Provide information here and then reassign to me.

**Comment by cebriggs7135** [comment]
Waiting for the first scRNAseq metadata.tsv submissions. The metadata.tsv just went out yesterday (Monday). Due Thursday (tomorrow).

**Comment by mccalluc** [comment]
Ideally they have a spec for the submissions before they start submitting? or maybe not.

**Comment by mccalluc** [comment]
@cebriggs7135 : Any progress?

**Comment by cebriggs7135** [comment]
Regarding your request: here's a Globus directory containing scRNAseq (SNAREseq2-RNA) 
<img width="430" alt="Screen Shot 2020-05-17 at 5 08 31 PM" src="https://user-images.githubusercontent.com/8284878/82240087-d3798a00-9907-11ea-9b6a-b8a5f8349202.png">

**Comment by mccalluc** [comment]
Cool - reopening and assigning to self to implement.

**Comment by mccalluc** [comment]
@cebriggs7135 : So can we require that a submission consist of:
- One `.list` file.
- Any number of `.fastq` or `fastq.gz` files.
- and I would prefer not to allow submission of extra Excel files... is that ok?

(We're not going to validate the content of files, but do you understand what the `.list` is for? It looks like this:
```
C1      C2      C3      C4      C5      C6      C7      C8      C9      C10     C11     C12
D1      D2      D3      D4      D5      D6      D7      D8      D9      D10     D11     D12
G1      G2      G3      G4      G5      G6      G7      G8      G9      G10     G11     G12
H1      H2      H3      H4      H5      H6      H7      H8      H9      H10     H11     H12
```
How is that used?)

**Comment by cebriggs7135** [comment]
@mccalluc That looks like the left half of a 96-well plate of sequencing reactions. (rows A-H, columns 1-12). Let me ask the submitters of this example dataset above.

**Comment by mccalluc** [comment]
*All* directory schemas need to be filled in. Closing per-assay-type issues.
