### ISSUE TITLE
Additional docs for sc-rna-seq

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#184]
@cebriggs7135 : IF you can give me a google docs link, I'll point to it from the docs here.

**Comment by cebriggs7135** [comment]
Sorry I don't know what google doc you are referring to.

**Comment by mccalluc** [comment]
Is there a sc-rna-seq doc analogous to [this](https://docs.google.com/document/d/1CYYSXPQjwdbvmvZaEcsi_2udvDfGEZrMyh4yFnm4p3M/edit#) for CODEX, or [this](https://docs.google.com/document/d/1Lrzruebio9nUusaFSJQlZGANkRjS5lrJmk4W0sSj_xM/edit#) for ATAC-seq?

**Comment by mccalluc** [comment]
@cebriggs7135 : Any progress on this?

**Comment by cebriggs7135** [comment]
Here is the current draft: 
https://docs.google.com/document/d/19UxMLaqIVt2Bd6zcdwbLn8W10KsoHk0cpU5UXP38_GA/edit#heading=h.gjdgxs
It's almost done. When confirmed as finalized, a copy will be made, with the metadata tables for bulk- and sc-RNAseq replaced by the Githib links to the schema for each).  The copy linked above will be an archived copy retaining the metadata table.

**Comment by mccalluc** [comment]
@cebriggs7135 : What I want is the final url that I can put in the yaml, and it sounds like this url isn't it. Ping me when there is a final URL? Thanks!
