### ISSUE TITLE
Double-check stanford codex file structure

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#186]
Are the examples in the original docs accurate, or should the same changes Akoya required be applied to Stanford? Better to sort this out first, rather than waiting for Joel to report that it doesn't validate.

**Comment by cebriggs7135** [comment]
What Akoya changes are you referring to?

**Comment by mccalluc** [comment]
https://github.com/hubmapconsortium/ingest-validation-tools/pull/185/files#diff-b6a962c57b438b73cf6a317b3d94a4cc

**Comment by mccalluc** [comment]
@cebriggs7135 - Please close this is there is nothing to do.

**Comment by cebriggs7135** [comment]
I'm not sure how to read the changes denoted here to answer your question. Can we look at this together?
<img width="501" alt="Screen Shot 2020-05-17 at 4 51 13 PM" src="https://user-images.githubusercontent.com/8284878/82159777-c5bbfa00-985e-11ea-9f00-b3bbd7641fac.png">
