### ISSUE TITLE
Add “library_id” and “is_sequencing_replicate” to the sc/snRNA metadata.tsv

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#189]
Dinh requests addition of these 2 fields to the scRNAseq metadata form.These should be optional fields since only certain assays like SNARE2-RNAseq will use them.

**Comment by mccalluc** [comment]
put it next to other library stuff

**Comment by mccalluc** [comment]
@cebriggs7135 : Please provide description text

**Comment by cebriggs7135** [comment]
Will do as soon as those fields are added.
