### ISSUE TITLE
Create Metadata.tsv for MALDI IMS (imaging mass spectrometry)

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#190]
Vanderbilt provided an excel spreadsheet of the required metadata filenames.

**Comment by mccalluc** [comment]
@cebriggs7135 : Can you please link to it or paste the text here? I'm not sure when I'll get to this, and with our slack subscription, information just disappears after a while.

**Comment by cebriggs7135** [comment]
[VAND_IMS_metadata.xlsx](https://github.com/hubmapconsortium/ingest-validation-tools/files/4554394/VAND_IMS_metadata.xlsx)
