### ISSUE TITLE
Create Metadata.tsv for AF (autofluorescence) Microscopy

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#191]
Vanderbilt provided an excel spreadsheet of the required metadata filenames.

**Comment by mccalluc** [comment]
@cebriggs7135 : please link or paste.

**Comment by cebriggs7135** [comment]
[VAND_AF_metadata.xlsx](https://github.com/hubmapconsortium/ingest-validation-tools/files/4554391/VAND_AF_metadata.xlsx)
