### ISSUE TITLE
Ensure that filenames are specific to assay types

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/ingest-validation-tools#198]
The filenames in this directory should be made more specific to the assay type, at least including either bulk or single-cell (sc) in the name:

https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/src/ingest_validation_tools/table-schemas

For example, for "atacseq.xml" it is not clear what assay this is referring to.

**Comment by mccalluc** [comment]
@cebriggs7135 : Tell me what the new names should be, and I'll do it.

**Comment by mccalluc** [comment]
Chris:
> there should be scatacseq, scrnaseq, bulkatacseq and bulkrnaseq assays

**Comment by mccalluc** [comment]
@cebriggs7135 : Sorry for the follow-up question, but was there something I should do beside make a copy of `atacseq` and `scrnaseq`? Unless there are differences in metadata we need to record, I don't think we should needlessly duplicate files.

**Comment by mccalluc** [comment]
Action item is just to change name to `sc...`; spec for bulk will arrive shortly.

**Comment by mccalluc** [comment]
The one action item was to rename atacseq to scatacseq. Completed in #233. If there are precise requests beyond that, reopen or file a new issue.
