### ISSUE TITLE
error in scrnaseq validation

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#222]
I keep getting this, with and without the: after  "scrnaseq" in the command --
NOTE: sc_isolation_enrichment has empty cells for a few of the rows & I tried replacing those with "na". Still doesn't work.

christinebriggs$ src/validate_submission.py --output as_text --type_metadata scrnaseq:/Users/christinebriggs/dropbox/HMS/INGEST_WORK/RNAseq/scRNAseq/UFlorida/UF_10X_metadata_050520.tsv
usage: validate_submission.py [-h]
                              [--local_directory PATH | --globus_url URL | --globus_origin_directory ORIGIN_PATH]
                              [--type_metadata TYPE PATH [TYPE PATH ...]]
                              [--optional_fields FIELD [FIELD ...]]
                              [--dataset_ignore_globs GLOB [GLOB ...]]
                              [--submission_ignore_globs GLOB [GLOB ...]]
                              [--output {as_browser,as_html,as_md,as_text,as_yaml}] [--add_notes]

type_metadata should be a list with an even length
christines-MacBook-Pro:ingest-validation-tools christinebriggs$

[UF_10X_metadata_050520.tsv.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/4582994/UF_10X_metadata_050520.tsv.txt)

**Comment by mccalluc** [comment]
works for me:
```
$ src/validate_submission.py --output as_text --type_metadata scrnaseq ~/Downloads/UF_10X_metadata_050520.tsv
No errors!
```

I'll get on slack and ask if you can zoom.
