### ISSUE TITLE
Make tissue_id format more flexible

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#235]
The current pattern constraint for tissue_id is -  
 "[A-Z]+[0-9]+(-[A-Z0-9]+)+"

Vanderbilt LC-MS tissue_ids are more complex - 

- The value "VAN0001-RK-1-1_5" in row 2 and column 2 ("B") does not conform to
      the pattern constraint of "[A-Z]+[0-9]+(-[A-Z0-9]+)+"
    - The value "VAN0003-LK-32-29_35" in row 3 and column 2 ("B") does not conform
      to the pattern constraint of "[A-Z]+[0-9]+(-[A-Z0-9]+)+"
    - The value "VAN0005-RK-4-224_228" in row 4 and column 2 ("B") does not conform
      to the pattern constraint of "[A-Z]+[0-9]+(-[A-Z0-9]+)+"
    - The value "VAN0006-LK-2-4_8"

**Comment by mccalluc** [comment]
@shirey : Is this correct? I am not expecting to see underscores in these IDs, and that's one of the few constraints I have.

**Comment by cebriggs7135** [comment]
Jeff Spraggins and/or Elizabeth ar the ones to ask. I'll do that...

**Comment by shirey** [comment]
What is the definition of column  ("B")?
Jeff uses the underscore to denote multiple tissues.  It could be possible that the underscores could be modeled by multiple rows.
