### ISSUE TITLE
metadata_path should NEVER be regarded as interchangable with data_path

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#236]
I strongly disagree with this statement in the field list for bulkrna:
> metadata_path | For current purposes, same as data path. This definition will change when metadata.tsv is sibmitted with datasets in the future.

Encouraging the DRTs to confuse the data and metadata is the last thing we should do.

**Comment by cebriggs7135** [comment]
Ok. Let's find an appropriate alternative.

**Comment by mccalluc** [comment]
@cebriggs7135 : I'll assign to you: Feel free to point me to a write up which explains why this was thought to be useful, and I can think about an alternative, but I'm happy to minimize my involvement.

**Comment by cebriggs7135** [comment]
My understanding is that we accept the same path for data_ and metadata_ , but only for now because the data & metadata has to have been already uploaded in order to know the metadata_path. We do not have any metadata folders in Globus for the data already in Globus.
