### ISSUE TITLE
add enums to unit fields

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#237]
@cebriggs7135 : Is there any reason unit fields should not be enums? Let's update the schemas to account for this.

**Comment by cebriggs7135** [comment]
If we require certain unit, then we don't need an extra column for units because that implies the units are up to the submitter to choose. We could do that.

**Comment by mccalluc** [comment]
@cebriggs7135 : No, the request here is to enumerate the allowed values. Nils believes that even if there is only one unit in use, it is still better to be explicit and have it in the table.

**Comment by cebriggs7135** [comment]
OK. Then I'll have to find time to work through all the unit fields in all of the submissions we have so far and create a list. That will take some time.

**Comment by cebriggs7135** [comment]
[Metadata_Enumerated_Units-051120.xlsx](https://github.com/hubmapconsortium/ingest-validation-tools/files/4611941/Metadata_Enumerated_Units-051120.xlsx)
Here is a table listing the enumerate units for assays so fa.
