### ISSUE TITLE
unit for "rnaseq_assay_input_unit" / "dna_assay_input_unit"

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#249]

**Comment by cebriggs7135** [comment]
Please clarify.

**Comment by mccalluc** [comment]
We've decided that `*_unit` fields should be enums, to make sure data submitters use only the allowed values. What are the allowed values for these two?

**Comment by cebriggs7135** [comment]
Still waiting for Aaron or Maigan to respond....
