### ISSUE TITLE
Add "wgs" to allowed validations

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#254]
Running wgs validation generates this error:

Expected one of ['af', 'bulkatacseq', 'bulkrnaseq', 'codex', 'lcms', 'maldiims', 'mixif', 'scatacseq', 'scrnaseq', 'seqfish', 'stained'], not "wgs"
 
Also add WGS to allowed assay_type.

**Comment by mccalluc** [comment]
#265 I think fixes the first part of this, and 'WGS' is in the assay_type enum constraint... so I think that's it, but reopen or clarify if there is still a problem.
