### ISSUE TITLE
Change names: Level 1 assay_types "IMS positive" & "IMS negative"

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#283]
These should both have the prefix "MALDI_" because they describe the "maldiims" schema: https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/docs/maldiims

**Comment by cebriggs7135** [comment]
May reopen this be cause they assay is listed in Github as maldiims . But the assay_types are listed as "IMS positive" and "IMS negative". MALDI, DESI & SIMS are IMS positive or IMS negative. You don't see the word "MALDI" in the metadata.tsv unless you look at instrument-assay info.
![Screen Shot 2020-05-25 at 5 40 03 PM](https://user-images.githubusercontent.com/8284878/82844543-dc8dcc80-9eae-11ea-8a6c-4652eef59203.png)

**Comment by mccalluc** [comment]
@cebriggs7135 : Are you waiting for more information before reopening? I just want to be sure this doesn't get lost, if it matters...

**Comment by cebriggs7135** [comment]
Jeff Spraggins agrees the name of the assay_types "**IMS positive**" & "**IMS negative**" should in fact be "**MALDI-IMS positive**" and "**MALDI-IMS negative**" because there will be other IMS positive/negative assays in the future like **nanoDESI-IMS**, **SIMS-IMS**, **DESI-IMS**

**Comment by cebriggs7135** [comment]
Jeff Spraggins agrees the name of the assay_types "**IMS positive**" & "**IMS negative**" should in fact be "**MALDI-IMS positive**" and "**MALDI-IMS negative**" because there will be other IMS positive/negative assays in the future like **nanoDESI-IMS**, **SIMS-IMS**, **DESI-IMS**
