### ISSUE TITLE
maldiims schema appears to have changed

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#284]
@mccalluc Look at the metadata.tsvs for MALDI IMS & IMC. None of that text at the bottom belongs there:

https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/docs/maldiims
https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/docs/imc

![Screen Shot 2020-05-25 at 5 23 35 PM](https://user-images.githubusercontent.com/8284878/82843874-a7807a80-9eac-11ea-90be-85c392f1e10e.png)

**Comment by mccalluc** [comment]
@cebriggs7135 : These are the valid values for the field, and came in with PR #282, which had your approval in issue #141. The list will get shorter when it's only the types that are really valid (see PR #279).

I don't think any action is required here. Will close, but reopen if you disagree (Have second thoughts about #141, or would like a different format, etc.)

**Comment by cebriggs7135** [comment]
I see. Thanks.
