### ISSUE TITLE
Unspecified TO DO for MxIF schema

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#308]
https://github.com/hubmapconsortium/ingest-validation-tools/edit/master/src/ingest_validation_tools/table-schemas/level-2/mixif.yaml

<img width="218" alt="Screen Shot 2020-06-03 at 3 47 00 PM" src="https://user-images.githubusercontent.com/8284878/83682199-97098780-a5b1-11ea-8031-3a0166b68afe.png">

**Comment by mccalluc** [comment]
I'm not sure either... maybe it was connected to something at some point? I'll get rid of it.
