### ISSUE TITLE
define antibodies.tsv

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#33]
- antibody id
- antibody name
- protein name (https://www.ncbi.nlm.nih.gov/genome/doc/internatprot_nomenguide/)
- cycle number
- channel number
- link to metadata tsv (use the path as the ID)

**Comment by cebriggs7135** [comment]
@mccalluc You asked if this is still to be implemented.

I don't think so but I'll check with Alex to see if he remembers. 
The first 3 things in the list are available in HuBMAP Antibodies V2 log 
https://docs.google.com/spreadsheets/d/1-sY_PhE7XBScFuZxzmei8UVrbpsxeSbfhY0R_rkn-JE/edit#gid=0

and the cycle number & channel number are specific to each specific experiment. For instance, each CODEX dataset includes a json listing cycles of Ab hybridizations and channels (# channels to detect the dyes labels).
https://portal.hubmapconsortium.org/docs/assays/codex
![Screen Shot 2020-11-04 at 4 56 11 PM](https://user-images.githubusercontent.com/8284878/98172193-ecc6c080-1ebe-11eb-9e59-340133668fa9.png)

**Comment by cebriggs7135** [comment]
According to Alex:
"There are preliminary plans to maintain a database of this information for the HuBMAP project, which I believe was to be indexed by Uniprot IDs.  I’m attaching an image containing draft fields that I received in October. This will be one of the items discussed at the November Sci-Tech webinar.
 
It might be premature to decide on the format as we would want the names we collect to be able to link back to the validation system under design. Let me check with Bill as to what the current implementation timeline is, as I know he is reevaluating some timelines as two members have recently left his team. I think the original alpha timeline was February-ish."

**Comment by mccalluc** [comment]
Ok, sounds like this is not actionable now: Plans have changed.
