### ISSUE TITLE
Add an enum to sample_metadata "health_status" field

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#332]
Add "trauma" to health status enum. Vanderbilt has one living trauma patient donor.

**Comment by ngehlenborg** [comment]
Is this value consensus among all TMCs? Or a proposal from Vanderbilt? We should get buy-in from the people who helped put together the sample metadata table before finalizing this.

**Comment by cebriggs7135** [comment]
After improving the definition for this field so that all contingencies are accounted for, we don't need an extra field to designate trauma.
