### ISSUE TITLE
Why was lipidomics removed from LC-MS assay_type enums?

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#342]
Why was "MS (shotgun lipidomics)" removed:
https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/docs/lcms
![Screen Shot 2020-07-24 at 9 11 22 AM](https://user-images.githubusercontent.com/8284878/88394681-da9c9880-cd8d-11ea-925d-f1de1a1416a3.png)

**Comment by mccalluc** [comment]
Before the current list, [it was unconstrained](https://github.com/hubmapconsortium/ingest-validation-tools/blame/c838bcf841e04a780ce8849270804ae0e5e5e8ff/docs/lcms/README.md#L143)... PR #279 add the constraints, and you were involved in that. If you want to add to the accepted values, please do so. If I'm misunderstanding the question, reopen.
