### ISSUE TITLE
query TMCs to understand if they can run a Python script, Docker container, etc.

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/ingest-validation-tools#345]
@mccalluc Write note

@cebriggs7135 Send out to TMCs once we have a final version of the email

**Comment by mccalluc** [comment]
@cebriggs7135 : Note is written: https://docs.google.com/document/d/1UarRYKAbwbTvRG76TIvPWpcfMHKIiqB6ylkPn2WF334/edit

You should have edit privs: Revise as you think best.

**Comment by mccalluc** [comment]
Chris reported that most would be happy with just the repo; closing this task.
