### ISSUE TITLE
Check for non-ASCII characters?

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-validation-tools#347]
Not sure if you already have a check like this, but for the SeqFISH metadata.tsv file we had a Unicode NO-BREAK SPACE character (0xA0) that looked just like a regular ASCII SPACE character, and it broke the JSON we generated to send back to ingest-api.

**Comment by mccalluc** [comment]
We read the file with a [latin-1 encoding](https://github.com/hubmapconsortium/ingest-validation-tools/blob/master/src/ingest_validation_tools/submission.py#L19-L20), which I believe matches what Excel exports. Some people have accents in their names, and I would be reluctant to give them an unnecessary error. It sounds like you have a character encoding bug downstream: JSON can certainly work with unicode.

Closing for now, but reopen if you think there's a consensus that we should only support ASCII, or let me know if I can help with the character encoding problem downstream.
