### ISSUE TITLE
AF directory schema is tied to Vanderbilt: Needs to be generic

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#349]
> As defined here, AF would only support *K*idney data from *VAN*derbilt. That is too restrictive.

_Originally posted by @ngehlenborg in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0NDY2MTUwMjQ5/pull_requests/unread_timeline_

**Comment by cebriggs7135** [comment]
@mccalluc The link above goes nowhere so I can't see the problem you describe.

**Comment by mccalluc** [comment]
Not sure where that url came from: Here's the right one:
https://github.com/hubmapconsortium/ingest-validation-tools/pull/348#discussion_r468642426

**Comment by mccalluc** [comment]
Blank slate for directory structures. Closing.
