### ISSUE TITLE
PAS directory schema

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#383]
These will be published soon the portal. Ideally there would be a directory schema in place.

**Comment by ropelews** [comment]
Suggest the following (from vanderbilt):

`
# - A dataset consists of a single PAS stained microscopy run, and  
#   a set of transformation files that are useful for other
#   related datasets. (Vanderbilt)
-
  pattern: 'processedMicroscopy/*_PAS_images/*ome.tif'
  description: 'OME TIFF files (multichannel, multi-layered, image pyramids) produced by the PAS microscopy experiment'
-
  pattern: 'processedMicroscopy/*_PAS_transformations/*.txt'
  description: 'transformations to PAS (related) data'
-
  pattern: 'rawMicroscopy/*.xml'
  description: 'XML metadata file from the autofluorescence microscopy experiments'
-
# Note: extension might change depending on the microscope used. This is just for 
# Leica .scn which is a container with tiled scan images (bigtiff)
# which is the only type that we are currently receiving.
  pattern: 'rawMicroscopy/*.scn'
  description: 'raw microscope file for the experiment'`
