### ISSUE TITLE
Connecting ingest-validation-tools output to ingest-ui

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/ingest-validation-tools#388]
When ingest-validation-tools is run in the context of a submission to ingest-pipeline, the validation is triggered from the ingest-ui interface and any validation errors must be displayed in that interface.  We need access to validation errors in a form that can be flexibly displayed within ingest-ui.  The display page or dialog for those errors has not yet been designed.

**Comment by shirey** [comment]
@mccalluc Can we get a simple list of human (non-programmer) readable error messages- one string per found problem?  I'll need these to display the message to the user in the ingest-ui and would prefer just messages so I can easily format for display.

**Comment by jswelling** [comment]
The current ingest-pipeline code produces the flag version which @shirey wants, with the error list present when the flag says there are errors.  I'll need to produce the flag in any case.
