### ISSUE TITLE
Point to example for contributors.tsv... with other templates, if possible.

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#415]

**Comment by cebriggs7135** [comment]
Here is the doc Bill sent me. This came form Vanderbilt:
https://docs.google.com/spreadsheets/d/1JxnKZYsfr40dTNYv1h_eFk5_LsrDEQkLspUDBHOno-Y/edit?usp=sharing

Please clarify "other templates".
