### ISSUE TITLE
background document for samples?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#425]
Right now, it's `TODO`... Is there a google doc which didn't make it to portal-docs? or if there isn't one, just don't show the link? @cebriggs7135 , can you comment?

**Comment by cebriggs7135** [comment]
Do you mean the sample metadata.tsv?

**Comment by mccalluc** [comment]
Sorry, I meant this “sample”: https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/docs/sample

**Comment by mccalluc** [comment]
Chris writes:
> No. The fields are self explanatory.

So we should not display the link.
