### ISSUE TITLE
Create metadata schema for a new assay: SLIDEseq

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#428]
Here's a link to the spreadsheet for SLIDEseq metadata:
https://docs.google.com/spreadsheets/d/1KDBigt6Kqi7VRFb_uc3zkc17tedi4gz_oS0Y2T0fi08/edit?usp=sharing
 It's much the same as RNAseq except for a new puck_id column.

**Comment by mccalluc** [comment]
@cebriggs7135 : Do you mean bulkrnaseq? Or sc? Or something else?

**Comment by cebriggs7135** [comment]
SLIDEseq is most like single cell RNA seq because the RNA transcripts are captured on beads associated with spatial coordinates on a slide (rather than bead per cell).

Are these documents blockers to generating the assay metadata schema?

The directory structure doc here (1) & the assay document (2) are undergoing some updates by the Broad team per a sprint we (Alex & I) had with them on Wednesday:

(1) https://docs.google.com/document/d/1k3Q48rkL_ueA4_8NTaTLtBfNCG0fa8LwsXqP9O5gILo/edit?usp=sharing
(2) https://docs.google.com/document/d/1og-cHmOlfX0YIIfBqRnWnSe3w9_44T0KilN3GAxPnW8/edit?usp=sharing

**Comment by mccalluc** [comment]
@cebriggs7135: Confirm that the `sc_*` fields should be dropped, along with `library_id`?
```
scrnaseq:                               slideseq:

...
acquisition_instrument_vendor		acquisition_instrument_vendor
acquisition_instrument_model		acquisition_instrument_model
sc_isolation_protocols_io_doi	  <
sc_isolation_entity		  <
sc_isolation_tissue_dissociati	  <
sc_isolation_enrichment		  <
sc_isolation_quality_metric	  <
sc_isolation_cell_number	  <
rnaseq_assay_input		  <
rnaseq_assay_method			rnaseq_assay_method
library_construction_protocols		library_construction_protocols
library_layout				library_layout
library_adapter_sequence		library_adapter_sequence
library_id			  |	puck_id
is_technical_replicate			is_technical_replicate
...
```

**Comment by cebriggs7135** [comment]
That is not the correct template. The template is here:
https://docs.google.com/spreadsheets/d/1KDBigt6Kqi7VRFb_uc3zkc17tedi4gz_oS0Y2T0fi08/edit#gid=1112128153

**Comment by mccalluc** [comment]
@cebriggs7135 -- Could you make this comment on the active PR instead? Since that's the same URL you gave above, and can say more precisely what fields are missing?
