### ISSUE TITLE
Create antibody_metadata schema

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#431]
Here is a link to the template:
https://docs.google.com/spreadsheets/d/1ZzwL_-Ckj9jjQk2CD9utFcZmQFIqFkuUkuJQxVhAVq8/edit?usp=sharing

**Comment by mccalluc** [comment]
@cebriggs7135 : 
- dataset UUIDs are not known until after submission. Ok to remove this column?
- Please update the directory schema to reflect this: "Florida users should create a directory called "extras" and put this Ab tsv and the Ab validation report in it."
- Descriptions need to be provided.

I can start a PR, but there are gaps to be filled in.
