### ISSUE TITLE
tighter per-assay-type pattern constraint on channel_id

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#442]
Marda Jorgenson clarified for CODEX:
> channel_id is composed of :
> - acquisition cycle number (integer that would not go over 2 places- suspect it would be “1” if not applicable)
> - followed by a comma
> - followed by the antibody channel identifier or tag (alpha numeric string that is identical in format to what is present in the raw data)
>
> for us (at least in this release) the acquisition cycle number will =  “2” through “12” ( cycles 1 and 13  are first and last cycles and are blanks for background subtraction, so no antibodies are present in them)
>
> for CODEX, antibody channel identifier or tag will be one of 3 choices: “CH2” “CH3” or “CH4”….CH1 is always nuclear stain with no antibody present in CODEX runs.
>
> So an example of a channel_id would be  “2,CH3” alternative would be “cycle2,CH3”

**Comment by jswelling** [comment]
I'm a little troubled by the use of a comma as the separator, as converting to a csv file is a likely use case.  Would something like an underscore or hyphen be possible?

**Comment by mccalluc** [comment]
This is assay specific. For ingest-validation-tools, this will be unconstrained. Joel may implement additional tests in `-tests`.
