### ISSUE TITLE
Directory schema for scatacseq

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#451]
Just `.*\.fastq\.gz` with no description right now.

**Comment by cebriggs7135** [comment]
@mccalluc After a brief survey of scRNAseq & scATACseq submitters, data directories will contain only fast files. Can these data directory schema be finalized by you (since Alex does not respond) so that UWASH can run the validate_submission.py on their scATACseq submission directory?

**Comment by cebriggs7135** [comment]
@icaoberg The description may be as simple as : "fastq files contain the raw sequence reads generated my the assay".
Could you please merge this and do the same for the scRNAseq Directory structure as well? https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/docs/scrnaseq
