### ISSUE TITLE
The PDF of the Image Analysis Report for Codex Uploads Will Be Called "Image_Analysis_Report.pdf"

### ISSUE THREAD

**Issue by hHakimian** [hubmapconsortium/ingest-validation-tools#508]
As the title states. The pdf will be kept in the master folder, outside of both src and drv. I was asked by Christine Briggs to request this regex change from Chuck McCallum. Thank you for your time

Best,
Hunter Hakimian from UF

**Comment by mccalluc** [comment]
Replaced by #528
