### ISSUE TITLE
Add a lightsheet metadata template to Github

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#516]
https://docs.google.com/spreadsheets/d/1vInMtODnkYZkjfA0vpz3uxSmsJvwihYM5ZadwAIfxgw/edit?usp=sharing

into https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/docs

**Comment by cebriggs7135** [comment]
## @mccalluc UFLA is ready to submit lightsheet so they will need this doc soon.

**Comment by mccalluc** [comment]
@cebriggs7135 - Is there a directory schema and a document describing the assay?

**Comment by cebriggs7135** [comment]
Yes: https://drive.google.com/drive/folders/1qJ3_wq_qabT96AHAGWhBtFSMQCpPITgc?usp=sharing
