### ISSUE TITLE
Add "concentration" field to antibodies

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#524]
Depending on how an antibody preparation is obtained (purchased or custom made), data submitters can provide either the concentration or the dilution. The antibodies TSV currently has a dilution field. Add a concentration field with units constrained to ug/ml. dilution and concentration should be optional fields.

**Comment by mccalluc** [comment]
@cebriggs7135 : For context, is this being driven by a particular lab, or is it coming from multiple?

@ngehlenborg : This is not hard... but do you want a versioning scheme before we do this? and presumably there should be both `concentration` and `concentration_unit`?

**Comment by cebriggs7135** [comment]
@mccalluc @ngehlenborg This has so far come up for UFLA & GE, both about to submit antibodies metadata with custom antibodies. Will you be able to do this soon?

**Comment by ngehlenborg** [comment]
With versioning in place we can take the route proposed by @mccalluc (separate unit fields).

**Comment by cebriggs7135** [comment]
Making this an issue-requesting new version
