### ISSUE TITLE
Help users if they've autofilled protocol IDs, and the numbers have incremented.

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#540]
@cebriggs7135 :  Do we know that TMCs are actually unable to interpret the error? ... or is the error message just too verbose, but still intelligible?

**Comment by cebriggs7135** [comment]
The error is just 404, if the incremental-ized DOI doesn't exist. But sometimes, the wrong protocol DOI might be a real one for an unintended protocol.

**Comment by mccalluc** [comment]
Right: Data can just be wrong, but still be valid. If anything, this might be more of a problem with the rr_ids, which are just integers, and thus more likely to get false negatives.

Do you have a clear sense of what the behavior should be? Or are you stating a problem, and it's in my court to articulate a solution? Either is fine, just trying to figure out what the constraints are.

**Comment by cebriggs7135** [comment]
#the problem is caused by dragging from one cell down to fill the cells beneath  rather than copying the desired input & pasting it into the target cells.
