### ISSUE TITLE
validate_submission error message

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#554]
This is the error message for a FAKE_subm mission directory I've made for CellDive. What does it mean? (the data_folder is empty)

christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --local_directory /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/GE_CellDIVE/FAKE_submission/
Metadata TSV Errors:
  Missing: There are no effective TSVs.
Reference Errors:
  No References:
  - GE_CellDive-metadata_020521.tsv
  - .DS_Store
  - GE_contributors_020521.tsv
  - data_folder
  - GE_CellDive_antibodies_021721.tsv

christines-MacBook-Pro:ingest-validation-tools christinebriggs$

**Comment by mccalluc** [comment]
From the docs:
> Submissions are based on directories containing at a minimum:
> -  one or more `*-metadata.tsv` files.

`GE_CellDive-metadata_020521.tsv` does not match that pattern, so it can't find the metadata tsv.

**Comment by cebriggs7135** [comment]
I see. Thanks.
