### ISSUE TITLE
Collect values of enumerated fields, and deliver to Jonathan

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#567]
The thinking is that we really want to separate sheets:
- sheet one: type, fieldname, description (different types might use the same name different ways)
- sheet two: enumerated value, fieldname, field description

... but think a little more to make sure it's really something that will be useful to Jonathan.

**Comment by mccalluc** [comment]
@ngehlenborg, proposal:
| file_name | field | description | enum |
| --- | --- | --- | --- |
| ... | | | |
| af.yaml | resolution_z_value | ... |  |
| af.yaml | resolution_z_unit | ... | nm |
| af.yaml | resolution_z_unit | ... | um |
| ... | | | |

Basically, denormalize everything, so it's very redundant, particularly when we get to listing each value for an enum, but everything you want is in the row.
Jonathan is the user for this report? Should we check with him and see if this is the best format?

**Comment by ngehlenborg** [comment]
Checking with Jonathan would be best but I think the proposal is exactly what we need.
