### ISSUE TITLE
Create metadata schema for 3D-IMC

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#574]
The schema is here: 
https://docs.google.com/spreadsheets/d/1b7081qyMR7GPq50b-I9LzGdDdJEbMg2ME0JnpcQSVMc/edit?usp=sharing

It's similar to the current "IMC" schema except that 1 new fieldname has been added for 3D IMC:
number_of_sections

**Comment by cebriggs7135** [comment]
Please pause this work until further notice - 2 changes coming up.

**Comment by mccalluc** [comment]
@cebriggs7135 - I unassigned myself to take it off the radar: Reassign me when it's ready.

**Comment by cebriggs7135** [comment]
@mccalluc This is ready to go into GitHub: The schema is here:
https://docs.google.com/spreadsheets/d/1b7081qyMR7GPq50b-I9LzGdDdJEbMg2ME0JnpcQSVMc/edit?usp=sharing

**Comment by mccalluc** [comment]
@cebriggs7135 See above: Waiting for your review on #592.
