### ISSUE TITLE
Change scrnaseq sequencing_read_format to same as scatacseq

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#607]
The scatacseq sequencing_read_format is required and unconstrained.
The scrnaseq sequencing_read_format is required and constrained.  Please remove constraints for this field for scrnaseq.

- Does this change have buy-in from other groups providing the same kind of data?
- Can you quote or reference any outside documentation that motivates this change?
- Is this change backward compatible, or does it make validation more stringent?

@cebriggs7135 will evaluate this request, and if it can move forward,
will file a PR for @ngehlenborg to review,
and @mccalluc will make sure tests pass before merging.

**Comment by mccalluc** [comment]
@cebriggs7135 - To avoid repetition, templates are included by reference. So, on [scrnaseq.yaml](https://github.com/hubmapconsortium/ingest-validation-tools/blob/master/src/ingest_validation_tools/table-schemas/assays/scrnaseq.yaml), [sequencing.yaml](https://github.com/hubmapconsortium/ingest-validation-tools/blob/master/src/ingest_validation_tools/table-schemas/includes/sequencing.yaml) is included by reference.

... but, can you say in what way the constraints are two strict? What kinds of values are the TMCs providing? If we give it up, we give up the possibility of any machine processing of this data in the future, and I don't think we should rush into that.

**Comment by cebriggs7135** [comment]
@mccalluc the entries below in the scatacseq pass because there are no constraints but the same format in the scrnaseq is not passing and I can't figure out why:
![Screen Shot 2021-03-08 at 2 09 08 PM](https://user-images.githubusercontent.com/8284878/110369211-13853700-8018-11eb-9982-ed21746965e2.png)
![Screen Shot 2021-03-08 at 2 08 49 PM](https://user-images.githubusercontent.com/8284878/110369243-1ed86280-8018-11eb-96a0-8e4cf9dcfafa.png)

**Comment by mccalluc** [comment]
> Alternatively, leave atacseq with unconstrained delimiters and leave scrnaseq constrained to "/" delimiters.

So the status quo is acceptable? Then I'll close this, and file a new issue to:
- Apply consistent validation to this field.
- Add an example in the docs if people have trouble reading the regex.
