### ISSUE TITLE
validate_submission.py generates error: "no references from....

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#609]
When validating either scrnaseq or scatacseq directories, it sees the repeated references to ./data_path while also generating this:

*"There are no references from any TSV to data_path."*

Same for the contributors_path which points to that TSV file. When I remove STAN_snATAC_contributors.tsv, the message indicates it detects that that file is gone: 

*"In STAN_scrnaseq_metadata.tsv (as scrnaseq): External: row 9, contributors /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/STAN-Cotter/21_jan_release/scrnaseq/STAN_scRNA_contributors.tsv: File does not exist" *

This is what I get:
christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --local_directory /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/STAN-Cotter/21_jan_release/snatacseq/
.....
*There are no references from any TSV to STAN_snATAC_contributors.tsv.
There are no references from any TSV to .DS_Store.
There are no references from any TSV to data_path.
There are no references from any TSV to STAN_snATAC_contributors.tsv.
The dataset directory "./data_path" is referenced by STAN_snATAC_metadata.tsv (row 2), and somewhere else, but references should be unique.
The dataset directory "./data_path" is referenced by STAN_snATAC_metadata.tsv (row 3), and somewhere else, but references should be unique.
The dataset directory "./data_path" is referenced by STAN_snATAC_metadata.tsv (row 4), and somewhere else, but references should be unique.
The dataset directory "./data_path" is referenced by STAN_snATAC_metadata.tsv (row 5), and somewhere else, but references should be unique.
The dataset directory "./data_path" is referenced by STAN_snATAC_metadata.tsv (row 6), and somewhere else, but references should be unique.
The dataset directory "./data_path" is referenced by STAN_snATAC_metadata.tsv (row 7), and somewhere else, but references should be unique.
The dataset directory "./data_path" is referenced by STAN_snATAC_metadata.tsv (row 8), and somewhere else, but references should be unique.
christines-MacBook-Pro:ingest-validation-tools christinebriggs$ *

[STAN_snATAC_contributors.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6108427/STAN_snATAC_contributors.txt)
[STAN_snATAC_metadata.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6108429/STAN_snATAC_metadata.txt)

**Comment by mccalluc** [comment]
@cebriggs7135 :
> it sees the repeated references to ./data_path while also generating this: "There are no references from any TSV to data_path."

Right: `./data_path` != `data_path`. Remove the `./` in the TSV. If there's a reason './' needs to be included, reopen.
