### ISSUE TITLE
Add "PA" to valid sample_id in the sample metadata & tissue_id in assay metadata

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#616]
PA is pancreas, a new organ type. Please add this to 
constraint "pattern" for both sample_id and tissue_id. Currently, only these are allowed:
   "([A-Z]+[0-9]+)-(BL|BR|LB|RB|HT|LK|RK|LI|LV|LL|RL|LY\d\d|SI|SP|TH|TR|UR|OT)(-\d+)+(_\d+)?"

- Does this change have buy-in from other groups providing the same kind of data?
- Can you quote or reference any outside documentation that motivates this change?
- Is this change backward compatible, or does it make validation more stringent?

@cebriggs7135 will evaluate this request, and if it can move forward,
will file a PR for @ngehlenborg to review,
and @mccalluc will make sure tests pass before merging.

**Comment by mccalluc** [comment]
@cebriggs7135 : Looking in to this, this regex has already been simplified in `all_assays.yaml`:
```
  constraints:
    pattern: '([A-Z]+[0-9]+)-[A-Z]{2}\d*(-\d+)+(_\d+)?'
```

I don't think there is any argument for Sample to be different from Dataset.
