### ISSUE TITLE
validate_submission.py doesn't run on CODEX files

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#621]
It runs on this set of TSVs:

*christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_samples.py --path /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/CALT-UW-sciATACseq/CALT_sciATACseq_Sample.tsv
No errors!*

but not this CODEX set of TSVs, even though it did yesterday:

*christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --local_directory /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/STAN-Cotter/jan21_release/codex/*

It looks the same for 10 minutes ++++. But it ran yesterday.

**Comment by mccalluc** [comment]
> It looks the same for 10 minutes ++++.

Do you mean it freezes, and the program doesn't exit?

Have you updated to the latest version since yesterday? Trying to understand if I should be looking for the culprit in the code, or in the outside world.

Can you try using `--path` to the TSV in `/STAN-Cotter/jan21_release/codex/` and tell me what the result is?

Can you attach that TSV?

**Comment by cebriggs7135** [comment]
[STAN_CODEX_contributors.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6157796/STAN_CODEX_contributors.txt)
[STAN_CODEX_metadata.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6157797/STAN_CODEX_metadata.txt)
[STAN0007_antibodies.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6157799/STAN0007_antibodies.txt)
[STAN0008_antibodies.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6157800/STAN0008_antibodies.txt)
[STAN0009_antibodies.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6157802/STAN0009_antibodies.txt)

**Comment by mccalluc** [comment]
> Can you try using --path ...

I meant using `--path` on `src/validate_samples.py`... Do the TSVs validate in isolation, or it a problem with the submission as a whole?

**Comment by cebriggs7135** [comment]
I see the space before the date time.

**Comment by mccalluc** [comment]
I've added more logging, and it looks like it just has a lot of IDs to check... 168 antibodies entries, and a second or two for each, so it will take a while. I'll keep an eye on it and see if it blocks.

Things that would improve the experience for users:
- Logging as the requests are made, so they know that something is happening.
- Caching the results locally, so once we check a URL, we'll assume it's still good going forward.

**Comment by mccalluc** [comment]
... Real problem: the in-memory cache isn't being re-used on successive lines in the metadata TSV. This is on me.

**Comment by cebriggs7135** [comment]
@mccalluc The validation run still seems to stay stuck.
