### ISSUE TITLE
upgrade commons to v2.0.2

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#629]
Believe it just loosens constraints, so shouldn't cause problems.

See also https://github.com/hubmapconsortium/portal-ui/issues/1660

**Comment by mccalluc** [comment]
@yuanzhou -- There actually isn't any commons dependency in ingest-validation-tools: In the larger Airflow system managed by Joel, yes, but not in this codebase. Closing: No action.

**Comment by yuanzhou** [comment]
Good to know, thanks.
