### ISSUE TITLE
Clear cache on validate_submission.py runs

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#654]
2 antibodies in Stanford's CODEX datasets got flagged last week because antibodiesregistry.org had to delay their release until Monday of this week. They emailed me on Monday to notify me that they were published and on the website. However, they keep coming up as: 

 "AB_2890053" fails because URL returned 404: "https://scicrunch.org/resolver/RRID:AB_2890053".
 "AB_2890054" fails because URL returned 404: "https://scicrunch.org/resolver/RRID:AB_2890054"

Click on the links and you'll see they are in fact published to the site.
Are they cached? If so, how can I clear the cache?

**Comment by mccalluc** [comment]
The cache is the file `src/ingest_validation_tools/url-status-cache.db`. 
- Would it be best to clear the cache on every run?
- or add a note in the error message pointing out this file, and leave it to the user to delete manually?
- or provide `--keep_url_cache` that would preserve it across runs?
- or default the other way and add `--clear_cache` to explicitly clear the cache?

I would lean towards the last, but you're closer to the users...

**Comment by cebriggs7135** [comment]
I agree. Add  --clear cache so users like me can clear the cache at will.
