### ISSUE TITLE
Questions from Joel on antibodies versioning

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#659]
Assuming a TSV with these columns: 
```
version channel_id  antibody_name   rr_id   uniprot_accession_number    lot_number  dilution    concentration_value concentration_unit  conjugated_cat_number   conjugated_tag
```

> - Should it be valid if all the given columns are present, but 'version' has no entries?  I think it should not be valid, and that is the true behavior.
> - Should it be valid if the 'version' column is absent?  I think it should be, because I thought there was a defaulting behavior, but it is not valid.
> - If the version and concentration_value columns are present, but the concentration_unit column is not, should it be valid?  I thought it should because _unit fields were optional, but it is not valid.
> - If the version column is filled with 1 values but the concentration_ columns are absent, should it be valid?  I think it should be valid, but it is not.

**Comment by mccalluc** [comment]
> Should it be valid if all the given columns are present, but 'version' has no entries? I think it should not be valid, and that is the true behavior.

Correct: if `version` is present, it is a required field.

> Should it be valid if the 'version' column is absent?  I think it should be, because I thought there was a defaulting behavior, but it is not valid.

No: If there is no version column, it is version 0, but v0 antibodies does not have `concentration_value` or `concentration_unit`, so validation will fail. That said, an antibodies TSV that validated before versioning (ie, has no `version` column) should still validate, because it has the correct v0 columns.

> If the version and concentration_value columns are present, but the concentration_unit column is not, should it be valid?  I thought it should because _unit fields were optional, but it is not valid.

First, by saying the `concentration_unit` column is not present, you actually mean that the column is there, but there are no values, right? The columns for each version are prescribed, and even if you do not have a value for an optional field, the column must still be present.

So I assume you mean you have a value for `concentration_value` but not for `concentration_unit`: That is not valid. I think you may be thinking of #647: That makes `_unit` fields _conditionally_ optional. If a value is not required, we don't need units... but if a unit is given, then units are required.

So the behavior you describe is not a bug: It should not be valid.

- If the version column is filled with 1 values but the concentration_ columns are absent, should it be valid?  I think it should be valid, but it is not.

That could be a bug. Can you provide the TSV in question, and the errors you see?

**Comment by jswelling** [comment]
In trying to reproduce the bug I've found that the version of ingest-validation-tools in my release 1.5.2, 9685fd4, does show the bug but the current HEAD of master on ingest-validation-tools does not.  So somewhere along the line the bug got fixed.  Consequently I'm closing this issue.

**Comment by mccalluc** [comment]
At that version, v2 of antibodies had been introduced, but I did not know that backwards compatibility was a requirement, so the _only_ version that will validate is v2. (In `src`, there is only the [v2 schema](https://github.com/hubmapconsortium/ingest-validation-tools/blob/9685fd46bdcb0802661ebc69a9abe25f4bbaffef/src/ingest_validation_tools/table-schemas/antibodies.yaml).) Since then, as you've noted, backward compatibility was added.
