### ISSUE TITLE
--clear_cache not recognized after git pull

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#660]
christines-MacBook-Pro:ingest-validation-tools christinebriggs$ git pull
christines-MacBook-Pro:ingest-validation-tools christinebriggs$ --clear_cache
bash: --clear_cache: command not found

**Comment by mccalluc** [comment]
- #655 has not been merged. Thank you for approving, but that doesn't automatically make it available in the master branch.
- It's not an independent command. It will be a flag on `validate_submission.py`. See the [updated documentation in the PR](https://github.com/hubmapconsortium/ingest-validation-tools/pull/655/files#diff-4e256f156d13c98b883f5b5eab4c26ece4704c0aae85612be22c6fcafbe12d36).
