### ISSUE TITLE
Maps in the YAML for ontology backed enums

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#663]
We're going to go with an approach where the TSVs contain human-readable strings, and these are expanded to ontology URIs (from a predefined list) in a later phase of ingest.

For the test run, I would suggest first doing this with the Donor YAML. It's not actually used for anything, so tweaks there shouldn't cause anyone any trouble, and we won't have tons of merge conflicts. (Why do we even have the Donor YAML? Even though Donor metadata has an entirely different ingest route, I think Jonathan felt that for the sake of documentation, it should be included here.)

What needs to be done? (*Italics* may need more attention, clarification.)
- For enums, which currently are lists, maps will be allowed, with the keys being the human-readable strings, and the values the URIs. (Normally, I'd say the URIs would be better keys, but in this case, I'm mostly concerned about keeping the yaml readable, so I want the human readable on the left.)
- When one of these mapped enums is encountered during doc generation, the docs will be more informative... perhaps there's a separate table of term/URI pairs. *Let me know if there are more requirements here.*
- When one of these mapped enums is encountered during template generation, the pull-down will have an extra value, and the sheet will have an extra, optional, column next to the enumerated column.
- *This none-of-the-above options will still cause a validation error: Chuck would really prefer to have a shared understanding with the TMC that if they are suggesting new terms, some errors will be expected.*
- *We do not forbid users from selecting a value, and entering a value in the adjoining free text field... They really shouldn't, but maybe they want to suggest a refinement on the main term? In any case, adding conditional validation on the free-text field is more complexity I'd like to avoid. Sorting this out is a curation responsibility.*
- Finally, there is a standalone script that complements the column with terms by adding a column with the URIs. This will be incorporated, somehow, into Joel's workflow, and will run after the last validation. (This expanded schema will not validate, because of the additional columns, but that seems ok.)
- Finally, finally, update the process diagram on the readme to point at https://docs.google.com/drawings/d/11DLkPe_mfC3kh69HCYqCx5MAVTTkYOXqVjyFY85jMLQ/edit

**Comment by cebriggs7135** [comment]
@mccalluc Can you explain this sentence in further detail because I'm not sure what "doc generation" means or refers to?

*When one of these mapped enums is encountered during doc generation, the docs will be more informative... perhaps there's a separate table of term/URI pairs. Let me know if there are more requirements here.*

**Comment by mccalluc** [comment]
@cebriggs7135 -- By "doc generation" I mean the step that builds the readable markdown, as well as the templates: So the latter is a subset.

**Comment by cebriggs7135** [comment]
@mccalluc Who sees the "readable markdown"? 

You say "one of these mapped enums is encountered during doc generation".

I don't understand what process you're talking about here. When & where does this encounter happen? Maybe we need to zoom on Tuesday.

**Comment by mccalluc** [comment]
Fixed in #672. We don't actually have any ontology backed terms, but the machinery is in place.
