### ISSUE TITLE
error on validation of HCA 10x metadata

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#675]
[HCA_LIVER_10X_metadata.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6313786/HCA_LIVER_10X_metadata.txt)
Error message re: No such file or directory: scrnaseq-hca-hca-v0.yaml.
Is this a typo in the yaml name?

*The data_path & contributors_path fields are optional but I get this error if I leave them blank:*

christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --local_directory /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/HCA/HCA_10X_TESTRUN/
In HCA_LIVER_10X_metadata.tsv (as scrnaseq-hca): Internal: No such file or directory: scrnaseq-hca-hca-v0.yaml.
In the dataset /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/HCA/HCA_10X_TESTRUN referenced on row 2, the file "HCA_LIVER_10X_metadata.tsv" is not allowed.
In the dataset /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/HCA/HCA_10X_TESTRUN referenced on row 2, the file "data_path/.DS_Store" is not allowed.
In the dataset /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/HCA/HCA_10X_TESTRUN referenced on row 2, the file "data_path/test.fastq.gz" is not allowed.
In the dataset /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/HCA/HCA_10X_TESTRUN referenced on row 2, a file matching "[^/]+\.fastq\.gz" is required but missing.
In HCA_LIVER_10X_metadata.tsv (as scrnaseq-hca): External: row 2, contributors

*for every row and then this at the end:*
/Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/HCA/HCA_10X_TESTRUN: Expected a TSV, but found a directory.

*Next, I put together a submission directory with a single folder called data_path containing a single file called test.fastq.gz & this 
./data_path
in every cell in the data_path field.*

*I get this error:*
In HCA_LIVER_10X_metadata.tsv (as scrnaseq-hca): Internal: No such file or directory: scrnaseq-hca-hca-v0.yaml.

*and this error for every row (121 rows):*

*In HCA_LIVER_10X_metadata.tsv (as scrnaseq-hca): External: row 2, contributors /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/HCA/HCA_10X_TESTRUN: Expected a TSV, but found a directory.*

**Comment by mccalluc** [comment]
@cebriggs7135 -- #673 has not been merged, so you will still have the same problems you had yesterday. You can see that [scrnaseq-hca](https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/docs/scrnaseq-hca) still does not have the source_project column. Closing.
