### ISSUE TITLE
scrnaseq-hca reduce error messages

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#676]
Both contributors_path and data_path are optional. 
I leave the contributors_path empty and I leave the true fastq.gz filenames for this project in the data_path field because that info will be needed to associate each HCA dataset with the actual HCA fastq.gz files Matt has uploaded. 

The problem is that I get this message for every row:

*In the dataset /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/HCA/HCA_10X_TESTRUN/TLH_2nd_wash_S3_L001_I1_001.fastq.gz referenced on row 2, the file "/Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/HCA/HCA_10X_TESTRUN/TLH_2nd_wash_S3_L001_I1_001.fastq.gz" does not exist.
In HCA_test_Liver-metadata.tsv (as scrnaseq-hca): External: row 2, contributors /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/HCA/HCA_10X_TESTRUN: Expected a TSV, but found a directory.*

1) Why is the empty contributors_path fields seen as containing a directory? Can that message be omitted?
2) Can you omit the "does not exist" messages in the data_path column?

**Comment by mccalluc** [comment]
> Why is the empty contributors_path fields seen as containing a directory? 

Without a file, the last element in the path is a directory. -- This is a bug.

> Can that message be omitted?

yes,

> Can you omit the "does not exist" messages in the data_path column?

Could you just use `--tsv_paths` instead of `--local_directory`?
