### ISSUE TITLE
bug in validation of HCA scrna metadata TSV

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#688]
@mccalluc The attached file is formatted as an HCA scrna file. It validates with --tsv_paths
but not with --local_directory:

christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --clear_cache --tsv_paths /Users/christinebriggs/dropbox/HMS/INGEST_WORK/CONTRIBUTORS_TSVs_2020/Fake_HCA10x_metadata.tsv
Fetching un-cached url: https://dx.doi.org/10.17504/protocols.io.btdpni5n
No errors!

christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --clear_cache --local_directory /Users/christinebriggs/dropbox/HMS/INGEST_WORK/CONTRIBUTORS_TSVs_2020/
Fetching un-cached url: https://dx.doi.org/10.17504/protocols.io.btdpni5n
Fetching un-cached url: https://orcid.org/0000-0002-7154-5361
Fetching un-cached url: https://orcid.org/0000-0002-7792-3749
Fetching un-cached url: https://orcid.org/0000-0002-2451-0633
In the dataset /Users/christinebriggs/dropbox/HMS/INGEST_WORK/CONTRIBUTORS_TSVs_2020 referenced on row 2, the file "CALT_SeqFISH_2020_contributors.tsv" is not allowed.
In the dataset /Users/christinebriggs/dropbox/HMS/INGEST_WORK/CONTRIBUTORS_TSVs_2020 referenced on row 2, the file "Fake_HCA10x_metadata.tsv" is not allowed.
In the dataset /Users/christinebriggs/dropbox/HMS/INGEST_WORK/CONTRIBUTORS_TSVs_2020 referenced on row 2, a file matching "[^/]+\.fastq\.gz" is required but missing.
There are no references from any TSV to .DS_Store.
Hint: If validation fails because of extra whitespace in the TSV, try:
src/cleanup_whitespace.py --tsv_path original.tsv > clean.tsv.
[Fake_HCA10x_metadata.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6359061/Fake_HCA10x_metadata.txt)
[CALT_SeqFISH_2020_contributors.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6359302/CALT_SeqFISH_2020_contributors.txt)

**Comment by mccalluc** [comment]
@cebriggs7135 -- We concluded that the fix is to include a datapath... but because the result of a missing datapath is not obvious (ie, the submission directory is taken as the dataset directory) we might include a warning just to make this more explicit... or maybe we don't try to read datasets if there is not a datapath? Filed #690, closing this... but reopen if I'm misremembering the plan.
