### ISSUE TITLE
Change af-microscopy and stained-microscopy directory schema: camelCase to snake_case

### ISSUE THREAD

**Issue by NHPatterson** [hubmapconsortium/ingest-validation-tools#700]
- Does this change have buy-in from other groups providing the same kind of data?
To date, Vanderbilt TMC is the only TMC producing these assays and we buy in, unanimously. 

- Can you quote or reference any outside documentation that motivates this change?
No need, just removes inconsistencies between file names ( snake_case like) and `rawMicroscopy` and `processedMicroscopy`. Change to `raw_microscopy` and `processed_microscopy`. 
- Is this change backward compatible, or does it make validation more stringent?
This would be a breaking change with previous data, so perhaps both cases can be allowed..

Relevant schemas:
https://github.com/hubmapconsortium/ingest-validation-tools/blob/12265bad2fd4cc17428d7ee65fb1dff2c91dfc84/src/ingest_validation_tools/directory-schemas/stained.yaml

https://github.com/hubmapconsortium/ingest-validation-tools/blob/12265bad2fd4cc17428d7ee65fb1dff2c91dfc84/src/ingest_validation_tools/directory-schemas/af.yaml

**Comment by icaoberg** [comment]
@NHPatterson this issue has been addressed in branch `icaoberg-vanderbilt-update` cc @khanshawPSC
