### ISSUE TITLE
Include a signature on successful runs

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#703]
It won't actually tell us anything useful, but identical submissions will have the same signature.

**Comment by mccalluc** [comment]
@jswelling -- I think you proposed this, so I want to understand the motivation, so that what I do is as useful as possible.

First, are we on the same page about the [current process](https://docs.google.com/drawings/d/1Cicn-JUVU9QmfsP0CHtGPJkqCe08DlENlKR02leOiLg/edit)? In particular, if validation fails when Chris runs Airflow, it is the responsibility of the TMC to resolve the errors.

I think the change request is for the notification from the TMC to Curation to include a token... but I'm not sure what this changes: Should Curation then check the token against the dataset? I'm not sure what problem that would solve -- validation still either passes, or it doesn't, and if we're adding Curation steps we should be clear what the benefit is.

Instead of just an opaque token, I'd propose adding several summary lines to the output from `--add_notes`, and this option could be turned on in Airflow.
- Report the version hash of `ingest_validation_tools` being run. _Addresses a scenario where the TMC is just running different validation code than what is deployed on Airflow._
- For each metadata TSV, the number of rows. _This is easy to compare, and perhaps the TMC is just looking at a different set of files than Chris?_
- ... and perhaps a synopsis of the fields, taking the first character from each field name and concatenating them. _We have error messages when the columns aren't correct, but this would be a form where you could put one above the other on successive lines and transpositions / deletions would be easy to see_
- The output of `find . | sort | md5` on the submission directory, or something like that. _This would be opaque, but it would be a sanity check that people are looking at the same sets of files._

**Comment by mccalluc** [comment]
@jswelling -- Would anything here be useful? It did seem like an off-the-cuff remark, so if there's nothing that would actually make our lives easier, I'd like to close this.

**Comment by mccalluc** [comment]
@jswelling -- Not hearing anything, so I guess it's not important. Closing, but feel free to reopen and clarify.

**Comment by jswelling** [comment]
Gaah; I don't think I ever even found the issue.  Please feel free to add me as a reviewer.

**Comment by mccalluc** [comment]
@jswelling 
> Please feel free to add me as a reviewer.

There is nothing to review. If you think something is in my court, please let me know.
