### ISSUE TITLE
Change af, stained directory schema: "_transformations" folder and data files should be optional

### ISSUE THREAD

**Issue by NHPatterson** [hubmapconsortium/ingest-validation-tools#719]
### schemas affected:
`af`
`stained`

> - Does this change have buy-in from other groups providing the same kind of data?

I believe Vanderbilt is the only TMC producing these sorts of data. 

> - Can you quote or reference any outside documentation that motivates this change?

The transformations folder is specific to the spatial transformations to match IMS data and other microscopy images for a given tissue section(s) from Vanderbilt TMC. One can easily imagine another TMCs producing stained microscopy images that aren't spatially transformed at all (and we have some of these ourselves!), thus there would not be a "_transformations" folder and ".txt" file within it. Thus this should be optional but file extension checked if present in my view. I don't believe this data is at all used in the portal for visualization. It's a record of how raw microscopy data is spatially transformed to processed (both of which are provided as images already).

> - Is this change backward compatible, or does it make validation more stringent?

This makes the validation less stringent, more general and it remains backward compatible.

**Comment by icaoberg** [comment]
@NHPatterson by making the transformations folder optional, are you implying the other files, e.g. images, are required? cc @khanshawPSC

**Comment by NHPatterson** [comment]
This is a really great question. The truth is, for us at least, if the data does not have spatial transformations, the `processed_microscopy` image is simply a dump of the `raw_microscopy` image to `ome-tiff`. I know the pipeline for processing these images (https://github.com/hubmapconsortium/ome-tiff-pyramid) correctly uses the `processed_microscopy` version for creating the necessary files for visualization. Without adding the `ome-tiff` ourselves and leaving `_images` optional, a potential hang up could be some of these `raw_microscopy` images are multi-series (i.e., contain a label image, macro image, as well as the microscopy image) which I'm not sure is supported in the current pipeline but would otherwise would be compatible with the aforementioned pipeline. @ilan-gold would know better.

In our case, we will almost ALWAYS have a `processed_microscopy` version and only have a handful of datasets where this isn't the case. Regardless, for these cases we generate the image to `ome-tiff`. All that said, I think for now removing making the `_images` folder optional could cause issues.

Thanks for following up.
