### ISSUE TITLE
Modify definitions for barcode size and offset

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#83]
cell_barcode_offset definition should read:
Positions in the read at which the cell barcodes start. Cell barcodes are 3 x 8 bp sequences that are spaced by constant sequences (the offsets). First barcode at position 0, then 38, then 76. (Does not apply to SNARE-seq and BulkATAC)

cell_barcode_size definition should read:
Length of the cell barcode in base pairs. Cell barcodes are, for example, 3 x 8 bp sequences that are spaced by constant sequences, the offsets. (Does not apply to SNARE-seq and BulkATAC)

**Comment by mccalluc** [comment]
Will do. For copy-edits, you can also submit PRs, and that might be more direct.

**Comment by mccalluc** [comment]
> First barcode at position 0, then 38, then 76.

If that is an example of a value, perhaps rephrase to make that more clear?
