### ISSUE TITLE
Protocols.io_doi columns should accept no values entered (temporary error fix)

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#84]
The following 3 columns in the ATACseq ingest template should take no entry for now until DRTs obtain the protocols.io address:

- **library_construction_protocols_io_doi** (column AA)
- **sc_isolation_protocols_io_doi** (column Q)
- **sequencing_protocols_io_doi** (column D)

**Comment by mccalluc** [comment]
@cebriggs7135 : What is the timeline for actually having these, and is it a problem from all labs, or just one? Until ingest-validation-tools is actually integrated in the ingest pipeline, failures don't actually block anything.
