### ISSUE TITLE
Edit current Mass Spec schema & Create 2 new Mass Spec metadata schema

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#849]
The current LC-MS may be modified as described. (Chris)
The current MALDI IMS may be modified as described and renamed IMS. (Chris)
Create 2 new schema : gas chromatography mass spec and capillary electrophoresis mass spec. (Chuck)
https://docs.google.com/spreadsheets/d/1CSlYduFtki-j8p1iqglZsYPlELtyHwwrOdOSEgzIBYw/edit?usp=sharing

**Comment by mccalluc** [comment]
(@cebriggs7135 will prepare PRs.)

**Comment by mccalluc** [comment]
actually, it requires copying files, so I'll start.

**Comment by mccalluc** [comment]
Split into 4 separate issues for tracking:
- #855
- #856 
- #857 
- #858
