### ISSUE TITLE
Frictionless errors for 'resource temporarily unavailable' don't say which resource

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/ingest-validation-tools#862]
We are seeing errors like the following from ingest-validation-tools table_validator:
>   File "/hive/users/hive/hubmap/hivevm193-prod/ingest-pipeline/src/ingest-pipeline/submodules/ingest-validation-tools/src/ingest_validation_tools/table_validator.py", line 27, in get_table_errors
>    assert len(report['errors']) == 0, f'report has errors: {report}'
> AssertionError: report has errors: {'version': '4.0.0', 'time': 0.103, 'errors': [{'code': 'task-error', 'name': 'Task Error', 'tags': ['#general'], 'note': '[Errno 11] Resource temporarily unavailable', 'message': 'The task has an error: [Errno 11] Resource temporarily unavailable', 'description': 'General task-level error.'}], 'tasks': [], 'stats': {'errors': 1, 'tasks': 0}, 'valid': False}

(The line number has changed in the current code version but the mechanism remains the same).  Some resource being used to validate URLs is not available, but we can't tell from the output which one.

**Comment by mccalluc** [comment]
@jswelling : Please provide a reproducer.

**Comment by jswelling** [comment]
@mccalluc I don't know how to provide a reproducer for an intermittent error caused by a remote web site.

**Comment by mccalluc** [comment]
@jswelling : To reproduce, I can turn off wifi and remove `url-status-cache.db`. Working on fix.
