### ISSUE TITLE
Deprecate nanoDESI ... first case of deprecation

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#866]
- Should still be in generated docs.
- Will not be referenced as a possible schema for validation... which enables the name to be used elsewhere.

**Comment by mccalluc** [comment]
> I’m assuming the whole nano schema is to be deprecated: This means NanoDESI and NanoPOTS , right? I’m going to make one PR with this deprecation, and that will clear the way for it to come in under a new umbrella.

> Let me confirm the nanoPOTS part with Manxi.....
> waiting for her response.

**Comment by cebriggs7135** [comment]
@mccalluc Manxi says that nanoPOTS cannot go into the new IMS schema. Therefore, I recommend that you rename **nanoDESI/nanoPOTS** to just **nanoPOTS**. We could change the assay_type so it defaults to just nanoPOTS.

**Comment by mccalluc** [comment]
Ok... I'll remove nanoDESI from the enum, revert the flags on this schemas, but keep the UI code changes, so they are there when we do have something to deprecate.

I will ask Chris for re-review when those changes are ready.

**Comment by cebriggs7135** [comment]
@mccalluc Just received an update from Manxi that nanoPOTS may also be included with nanoDESI in the new IMS schema after all.
