### ISSUE TITLE
CODEX validates with a required file in top directory

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#870]
`src_[^/]+/cyc.*_reg.*_.*/.*_.*_Z.*_CH.*\.tif`
is a required file in the CODEX src/ directory but UFL CODEX datasets have validated with this in the top level instead of src/. 
and 
it validates with the wrong filename pattern.

Example here:
 /consortium/University of Florida TMC/00d1a3623dac388773bc7780fcb42797/

https://app.globus.org/file-manager?origin_id=24c2ee95-146d-4513-a1b3-ac0bfdb7856f&origin_path=%2Fconsortium%2FUniversity%20of%20Florida%20TMC%2F00d1a3623dac388773bc7780fcb42797%2F

**Comment by mccalluc** [comment]
@cebriggs7135 : There is nothing wrong here. I'm not sure what the misunderstanding is.
```
globus ls '24c2ee95-146d-4513-a1b3-ac0bfdb7856f:/consortium/University of Florida TMC/00d1a3623dac388773bc7780fcb42797/src_CX_20-006_SP_CC2-C/cyc013_reg001_201122_203933/' | head
1.gci
1_00001_Z001_CH1.tif
1_00001_Z001_CH2.tif
1_00001_Z001_CH3.tif
1_00001_Z001_CH4.tif
1_00001_Z002_CH1.tif
1_00001_Z002_CH2.tif
1_00001_Z002_CH3.tif
1_00001_Z002_CH4.tif
1_00001_Z003_CH1.tif
```
There are plenty of TIFF files in that subdirectory which satisfy the expression.

At the top level, `NAV_20-006_SP_CC2-C.tif` matches `[^/]*NAV[^/]*\.tif` in the schema.

Closing.
