### ISSUE TITLE
Typo fix in an "includes" file

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#875]
@mccalluc I'm not sure of the best way to edit an includes yaml.

"Mode of data collection in tandem MS assays. Either DDA (Data-dependent acquisition) or 

**DIA (Data-indemendent acquisition."**

Should be Data-independent

https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/src/ingest_validation_tools/table-schemas/includes

**Comment by mccalluc** [comment]
There is no process change. Submit a PR on https://github.com/hubmapconsortium/ingest-validation-tools/blob/master/src/ingest_validation_tools/table-schemas/includes/fields/data_collection_mode.yaml.

Unassigning myself.
