### ISSUE TITLE
library_final_yield_unit, rather than library_final_yield_ng

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#88]
Nils:
> So there should be library_final_yield and library_final_yield_unit

But is this worth the added complexity? Wait for confirmation from Nils.

**Comment by ngehlenborg** [comment]
Yes, this is how this is commonly done. In fact, measurements are often broken down into three components/columns: 1. quantity, 2. unit (as string), 3. unit (as ontology id). Here is an example:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/1216518/77971925-04512180-72be-11ea-964e-00ea27ff4b56.png">

(from: https://arxiv.org/pdf/1910.14623.pdf, page 13)
