### ISSUE TITLE
handle multiple analytes

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#885]
@mccalluc @ngehlenborg The new mass spec schema are about to be used by data providers. Manxi asked if it is possible to select more than one analyte in the mass spectrometry schema. She has a nanoDESI dataset in which she analyzed both lipids & metabolites. It is not currently possible to choose more than one so we should discuss adding one field per analyte type with TRUE or FALSE as possible input. For instance IMS lists these possible analytes:
protein, metabolites, lipids, peptides, phosphopeptides, or glycans

**Comment by mccalluc** [comment]
@cebriggs7135 : Is it likely that we'll want to support arbitrary sets eventually?

@ngehlenborg : I would suggest that we just add an `analyte_class_2` column for this assay, and at index time these can be combined into a multi-valued facet. Thoughts? Changing to boolean columns, or making the volume hold a list introduces more special cases to handle.

**Comment by cebriggs7135** [comment]
To be finalized after discussion at the next portal call.

**Comment by mccalluc** [comment]
@cebriggs7135 : Looking at the meeting notes, it seems that one dataset per assay type will not be a problem, so can you close this?
