### ISSUE TITLE
ims schema points to the url for maldi-ims

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#891]
The IMS yaml still has the maldi-ims doc url. Perhaps we should remove this pointer until the description on the portal is updated?

doc_url: https://portal.hubmapconsortium.org/docs/assays/maldi-ims

https://github.com/hubmapconsortium/ingest-validation-tools/blob/cebriggs7135/descriptions/src/ingest_validation_tools/table-schemas/assays/ims-v2.yaml

**Comment by mccalluc** [comment]
@cebriggs7135 -- I believe you have ownership of the content. Reassigning

**Comment by mccalluc** [comment]
@cebriggs7135 -- Please clarify: https://hubmapconsortium.github.io/ingest-validation-tools/ims/ still links to https://portal.hubmapconsortium.org/docs/assays/maldi-ims ... This is ok, and this issue was filed in error?
