### ISSUE TITLE
Airflow validation error on contributors.tsv

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#913]
This contributors TSV file passes local validation but generates the following error upon Airflow validation: 
There's no contact field in this file:

Metadata TSV Errors:
  ? /hive/hubmap/data/protected/California Institute of Technology TMC/cc7c63c6d10c762d1efebda45d2dc784/cc7c63c6d10c762d1efebda45d2dc784_sciATAC_metadata.tsv
    (as scatacseq)
  : External:
      row 2, data /hive/hubmap/data/protected/California Institute of Technology TMC/cc7c63c6d10c762d1efebda45d2dc784:
        Not allowed:
        - CALT_sciATACseq_contributors.tsv
Hint: 'If validation fails because of extra whitespace in the TSV, try:

  src/cleanup_whitespace.py --tsv_in original.tsv --tsv_out clean.tsv'

[cc7c63c6d10c762d1efebda45d2dc784_CALT_sciATACseq_contributors.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6851560/cc7c63c6d10c762d1efebda45d2dc784_CALT_sciATACseq_contributors.txt)

**Comment by mccalluc** [comment]
Followed up on Slack:
> contains a contributors TSV, and it’s failing because it’s not part of the directory schema for this assay type: You probably want to move it up to the upload directory, and then check that contributors_path is correct.
>
> (This is still the backlog, right? because if it’s not, it should be bounced back to the TMC.)
