### ISSUE TITLE
Version directory schemas

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#923]
Requested by @pecan88 -- requirements are unclear.

If an analogy is being made to metadata schemas, there, providers can provide metadata under an older schema. For directories, is the expectation that all versions of a directory will validate, or only the most recent one?

Also in metadata schemas, providers indicate which version of the schema they expect to validate under. Is that also a requirement for directory schemas? Need to determine how the version will be communicated.

**Comment by pecan88** [comment]
@mccalluc - @icaoberg and @khanshawPSC will need to define the implementation details.  Here's my attempt to answer your questions (deferring ultimately to what you and Ivan think best ...)

For directory validation, I'd guess only most recent one wrt new submissions.

We'll need providers to indicate which directory schema version the submission uses and the default would be to the most recent one - I believe this is how the metadata schema works.  @icaoberg & @khanshawPSC  - can you help correct any mis-assumptions / guesses on my part here?

**Comment by mccalluc** [comment]
Talked with Ivan.
- New data directories will include a `version.txt` that will be read, and used to determine the directory schema to use.
- `version.txt` will be persisted through the pipelines, so that we will be able to recover the version the submitter claimed the submission was.
- Ivan will clarify guidelines for when a new version is necessary. Adding a new optional field probably doesn't merit a new version.
- Ivan will also be responsible for declaring when an older version is no longer valid for submission. (Though it will be included in the documentation.)
- `version.txt` doesn't need to be a number: for CODEX, we can separate the schemas, and everything will be cleaner.

**Comment by mccalluc** [comment]
@pecan88 / @icaoberg / @jswelling : My understanding from the meeting today that is that directory schema versioning is not necessary, because Jonathan will do the political work to make sure all TMCs structure their data the same way.

If that turns out not to be feasible, Nils has said he will coordinate any future proposals to make sure the whole HIVE is in agreement about what needs to be done.
