### ISSUE TITLE
Fix typo on https://hubmapconsortium.github.io/ingest-validation-tools/

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#924]
"reivew" should be "review".
There's no obvious way to edit this Readme from https://github.com/hubmapconsortium/ingest-validation-tools/blob/main/docs/README.md

https://hubmapconsortium.github.io/ingest-validation-tools/

**Comment by mccalluc** [comment]
You can use the search box at the top of this window to find where a string comes from: [the only match](https://github.com/hubmapconsortium/ingest-validation-tools/search?q=reivew) is `docs/index.md`

**Comment by mccalluc** [comment]
@cebriggs7135 : This has not been fixed. Issues should be linked to the PR that will resolve them.

**Comment by cebriggs7135** [comment]
@mccalluc I just linked it by adding (hash)924 in a comment on https://github.com/hubmapconsortium/ingest-validation-tools/commit/6357d89e5b8ec9ca39780ec364106255c7287a03#commitcomment-54111064

**Comment by mccalluc** [comment]
Fixed in #930.
