### ISSUE TITLE
Unify assay_category enums

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#94]
Working on #56, I realize that the enums defined for assay_category don't match. Should it be:
- microscopy
- mass spec
- sequence

or 
- imaging
- mass_spectrometry
- sequence_data

(In #96, going with with the latter three)

**Comment by mccalluc** [comment]
@cebriggs7135 : Right now it is:

      - imaging
      - mass_spectrometry
      - sequence

**Comment by cebriggs7135** [comment]
Looks good!

**Comment by mccalluc** [comment]
No action required. Closing.
