### ISSUE TITLE
regex for library_adapter_sequence?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#95]
The one sample I have is
```
CTGTCTCTTATACACATCT+AGATGTGTATAAGAGACAG
```

Besides ATCG, what else is allowed?

**Comment by cebriggs7135** [comment]
Good question. I think that's all but maybe there are wildcards allowed. I'll try to find out.

**Comment by cebriggs7135** [comment]
The answer is **Nothing else besides A T G & C is expected in adaptor_sequences.**

**Comment by mccalluc** [comment]
@cebriggs7135 : That is not true. There is a plus: Could there by more than one?

**Comment by mccalluc** [comment]
Heard from DRTs that the "+" is only if double ended. Removing question tag.
