### ISSUE TITLE
Implement MIBI schema

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#967]
Based on
https://docs.google.com/spreadsheets/d/1svITiu82IC556PQmBy9kuizXbVDjZlPZFhJe2xet2qs/edit#gid=1468496505

@cebriggs7135 :
- Which of these fields are required?
- What are the allowed enumerations?
- Please make the types explicit.
- Please provide the descriptions as a separate column.

**Comment by cebriggs7135** [comment]
Field enums & required = T or F are pending from Mike Angelo.
