### ISSUE TITLE
output metadata schema version

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/ingest-validation-tools#968]
The metadata validation tool should output the applied schema version:

1. This information should be printed to standard out (e.g. if a particular command line flag is provided).
2. This information should be included at the top of the validation report.

@jswelling: please provide additional requirements if needed!

**Comment by mccalluc** [comment]
@ngehlenborg / @jswelling : Please clarify:
- Are you talking about the integer version numbers on schemas, git version hashes, or something else?
- If it's integer version numbers on schemas, there may be multiple metadata TSVs in an upload: In that case, you want the version number for each TSV?
- Ok to add this to the information returned by `--add_notes`, or do you need something distinct from that?
- Are both (1) and (2) important? In CLI usage, the report goes to STDOUT.
